// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// EdgePosts holds the string denoting the posts edge name in mutations.
	EdgePosts = "posts"
	// EdgeQuestions holds the string denoting the questions edge name in mutations.
	EdgeQuestions = "questions"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeLikePosts holds the string denoting the like_posts edge name in mutations.
	EdgeLikePosts = "like_posts"
	// EdgeLikeQuestions holds the string denoting the like_questions edge name in mutations.
	EdgeLikeQuestions = "like_questions"
	// EdgeFavoritePosts holds the string denoting the favorite_posts edge name in mutations.
	EdgeFavoritePosts = "favorite_posts"
	// EdgeFavoriteQuestions holds the string denoting the favorite_questions edge name in mutations.
	EdgeFavoriteQuestions = "favorite_questions"
	// EdgeFollowing holds the string denoting the following edge name in mutations.
	EdgeFollowing = "following"
	// EdgeFollowedBy holds the string denoting the followed_by edge name in mutations.
	EdgeFollowedBy = "followed_by"
	// Table holds the table name of the user in the database.
	Table = "users"
	// PostsTable is the table that holds the posts relation/edge.
	PostsTable = "posts"
	// PostsInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostsInverseTable = "posts"
	// PostsColumn is the table column denoting the posts relation/edge.
	PostsColumn = "user_posts"
	// QuestionsTable is the table that holds the questions relation/edge.
	QuestionsTable = "questions"
	// QuestionsInverseTable is the table name for the Question entity.
	// It exists in this package in order to avoid circular dependency with the "question" package.
	QuestionsInverseTable = "questions"
	// QuestionsColumn is the table column denoting the questions relation/edge.
	QuestionsColumn = "user_questions"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "comments"
	// CommentsInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	CommentsInverseTable = "comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "user_comments"
	// LikePostsTable is the table that holds the like_posts relation/edge.
	LikePostsTable = "user_like_posts"
	// LikePostsInverseTable is the table name for the UserLikePost entity.
	// It exists in this package in order to avoid circular dependency with the "userlikepost" package.
	LikePostsInverseTable = "user_like_posts"
	// LikePostsColumn is the table column denoting the like_posts relation/edge.
	LikePostsColumn = "user_like_posts"
	// LikeQuestionsTable is the table that holds the like_questions relation/edge.
	LikeQuestionsTable = "user_like_questions"
	// LikeQuestionsInverseTable is the table name for the UserLikeQuestion entity.
	// It exists in this package in order to avoid circular dependency with the "userlikequestion" package.
	LikeQuestionsInverseTable = "user_like_questions"
	// LikeQuestionsColumn is the table column denoting the like_questions relation/edge.
	LikeQuestionsColumn = "user_like_questions"
	// FavoritePostsTable is the table that holds the favorite_posts relation/edge.
	FavoritePostsTable = "user_favorite_posts"
	// FavoritePostsInverseTable is the table name for the UserFavoritePost entity.
	// It exists in this package in order to avoid circular dependency with the "userfavoritepost" package.
	FavoritePostsInverseTable = "user_favorite_posts"
	// FavoritePostsColumn is the table column denoting the favorite_posts relation/edge.
	FavoritePostsColumn = "user_favorite_posts"
	// FavoriteQuestionsTable is the table that holds the favorite_questions relation/edge.
	FavoriteQuestionsTable = "user_favorite_questions"
	// FavoriteQuestionsInverseTable is the table name for the UserFavoriteQuestion entity.
	// It exists in this package in order to avoid circular dependency with the "userfavoritequestion" package.
	FavoriteQuestionsInverseTable = "user_favorite_questions"
	// FavoriteQuestionsColumn is the table column denoting the favorite_questions relation/edge.
	FavoriteQuestionsColumn = "user_favorite_questions"
	// FollowingTable is the table that holds the following relation/edge.
	FollowingTable = "follows"
	// FollowingInverseTable is the table name for the Follow entity.
	// It exists in this package in order to avoid circular dependency with the "follow" package.
	FollowingInverseTable = "follows"
	// FollowingColumn is the table column denoting the following relation/edge.
	FollowingColumn = "user_following"
	// FollowedByTable is the table that holds the followed_by relation/edge.
	FollowedByTable = "follows"
	// FollowedByInverseTable is the table name for the Follow entity.
	// It exists in this package in order to avoid circular dependency with the "follow" package.
	FollowedByInverseTable = "follows"
	// FollowedByColumn is the table column denoting the followed_by relation/edge.
	FollowedByColumn = "user_followed_by"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldPhone,
	FieldNickname,
	FieldPassword,
	FieldAvatar,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "users"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"comment_user",
	"follow_follower",
	"follow_following",
	"post_user",
	"question_user",
	"user_favorite_post_user",
	"user_favorite_question_user",
	"user_like_post_user",
	"user_like_question_user",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	PhoneValidator func(string) error
	// NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	NicknameValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	AvatarValidator func(string) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByAvatar orders the results by the avatar field.
func ByAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatar, opts...).ToFunc()
}

// ByPostsCount orders the results by posts count.
func ByPostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPostsStep(), opts...)
	}
}

// ByPosts orders the results by posts terms.
func ByPosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByQuestionsCount orders the results by questions count.
func ByQuestionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuestionsStep(), opts...)
	}
}

// ByQuestions orders the results by questions terms.
func ByQuestions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuestionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLikePostsCount orders the results by like_posts count.
func ByLikePostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLikePostsStep(), opts...)
	}
}

// ByLikePosts orders the results by like_posts terms.
func ByLikePosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLikePostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLikeQuestionsCount orders the results by like_questions count.
func ByLikeQuestionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLikeQuestionsStep(), opts...)
	}
}

// ByLikeQuestions orders the results by like_questions terms.
func ByLikeQuestions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLikeQuestionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFavoritePostsCount orders the results by favorite_posts count.
func ByFavoritePostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFavoritePostsStep(), opts...)
	}
}

// ByFavoritePosts orders the results by favorite_posts terms.
func ByFavoritePosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFavoritePostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFavoriteQuestionsCount orders the results by favorite_questions count.
func ByFavoriteQuestionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFavoriteQuestionsStep(), opts...)
	}
}

// ByFavoriteQuestions orders the results by favorite_questions terms.
func ByFavoriteQuestions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFavoriteQuestionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFollowingCount orders the results by following count.
func ByFollowingCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFollowingStep(), opts...)
	}
}

// ByFollowing orders the results by following terms.
func ByFollowing(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFollowingStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFollowedByCount orders the results by followed_by count.
func ByFollowedByCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFollowedByStep(), opts...)
	}
}

// ByFollowedBy orders the results by followed_by terms.
func ByFollowedBy(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFollowedByStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PostsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PostsTable, PostsColumn),
	)
}
func newQuestionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuestionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QuestionsTable, QuestionsColumn),
	)
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
	)
}
func newLikePostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LikePostsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LikePostsTable, LikePostsColumn),
	)
}
func newLikeQuestionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LikeQuestionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LikeQuestionsTable, LikeQuestionsColumn),
	)
}
func newFavoritePostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FavoritePostsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FavoritePostsTable, FavoritePostsColumn),
	)
}
func newFavoriteQuestionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FavoriteQuestionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FavoriteQuestionsTable, FavoriteQuestionsColumn),
	)
}
func newFollowingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FollowingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FollowingTable, FollowingColumn),
	)
}
func newFollowedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FollowedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FollowedByTable, FollowedByColumn),
	)
}
