// Code generated by ent, DO NOT EDIT.

package userlikequestion

import (
	"backend/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldEQ(FieldUserID, v))
}

// QuestionID applies equality check predicate on the "question_id" field. It's identical to QuestionIDEQ.
func QuestionID(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldEQ(FieldQuestionID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldLTE(FieldUserID, v))
}

// QuestionIDEQ applies the EQ predicate on the "question_id" field.
func QuestionIDEQ(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldEQ(FieldQuestionID, v))
}

// QuestionIDNEQ applies the NEQ predicate on the "question_id" field.
func QuestionIDNEQ(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldNEQ(FieldQuestionID, v))
}

// QuestionIDIn applies the In predicate on the "question_id" field.
func QuestionIDIn(vs ...int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldIn(FieldQuestionID, vs...))
}

// QuestionIDNotIn applies the NotIn predicate on the "question_id" field.
func QuestionIDNotIn(vs ...int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldNotIn(FieldQuestionID, vs...))
}

// QuestionIDGT applies the GT predicate on the "question_id" field.
func QuestionIDGT(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldGT(FieldQuestionID, v))
}

// QuestionIDGTE applies the GTE predicate on the "question_id" field.
func QuestionIDGTE(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldGTE(FieldQuestionID, v))
}

// QuestionIDLT applies the LT predicate on the "question_id" field.
func QuestionIDLT(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldLT(FieldQuestionID, v))
}

// QuestionIDLTE applies the LTE predicate on the "question_id" field.
func QuestionIDLTE(v int) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.FieldLTE(FieldQuestionID, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQuestion applies the HasEdge predicate on the "question" edge.
func HasQuestion() predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, QuestionTable, QuestionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionWith applies the HasEdge predicate on the "question" edge with a given conditions (other predicates).
func HasQuestionWith(preds ...predicate.Question) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(func(s *sql.Selector) {
		step := newQuestionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserLikeQuestion) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserLikeQuestion) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserLikeQuestion) predicate.UserLikeQuestion {
	return predicate.UserLikeQuestion(sql.NotPredicates(p))
}
