// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/follow"
	"backend/internal/ent/predicate"
	"backend/internal/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FollowUpdate is the builder for updating Follow entities.
type FollowUpdate struct {
	config
	hooks    []Hook
	mutation *FollowMutation
}

// Where appends a list predicates to the FollowUpdate builder.
func (fu *FollowUpdate) Where(ps ...predicate.Follow) *FollowUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetUpdateTime sets the "update_time" field.
func (fu *FollowUpdate) SetUpdateTime(t time.Time) *FollowUpdate {
	fu.mutation.SetUpdateTime(t)
	return fu
}

// SetFollowerID sets the "follower_id" field.
func (fu *FollowUpdate) SetFollowerID(i int) *FollowUpdate {
	fu.mutation.ResetFollowerID()
	fu.mutation.SetFollowerID(i)
	return fu
}

// SetNillableFollowerID sets the "follower_id" field if the given value is not nil.
func (fu *FollowUpdate) SetNillableFollowerID(i *int) *FollowUpdate {
	if i != nil {
		fu.SetFollowerID(*i)
	}
	return fu
}

// AddFollowerID adds i to the "follower_id" field.
func (fu *FollowUpdate) AddFollowerID(i int) *FollowUpdate {
	fu.mutation.AddFollowerID(i)
	return fu
}

// SetFollowingID sets the "following_id" field.
func (fu *FollowUpdate) SetFollowingID(i int) *FollowUpdate {
	fu.mutation.ResetFollowingID()
	fu.mutation.SetFollowingID(i)
	return fu
}

// SetNillableFollowingID sets the "following_id" field if the given value is not nil.
func (fu *FollowUpdate) SetNillableFollowingID(i *int) *FollowUpdate {
	if i != nil {
		fu.SetFollowingID(*i)
	}
	return fu
}

// AddFollowingID adds i to the "following_id" field.
func (fu *FollowUpdate) AddFollowingID(i int) *FollowUpdate {
	fu.mutation.AddFollowingID(i)
	return fu
}

// AddFollowerIDs adds the "follower" edge to the User entity by IDs.
func (fu *FollowUpdate) AddFollowerIDs(ids ...int) *FollowUpdate {
	fu.mutation.AddFollowerIDs(ids...)
	return fu
}

// AddFollower adds the "follower" edges to the User entity.
func (fu *FollowUpdate) AddFollower(u ...*User) *FollowUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fu.AddFollowerIDs(ids...)
}

// AddFollowingIDs adds the "following" edge to the User entity by IDs.
func (fu *FollowUpdate) AddFollowingIDs(ids ...int) *FollowUpdate {
	fu.mutation.AddFollowingIDs(ids...)
	return fu
}

// AddFollowing adds the "following" edges to the User entity.
func (fu *FollowUpdate) AddFollowing(u ...*User) *FollowUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fu.AddFollowingIDs(ids...)
}

// Mutation returns the FollowMutation object of the builder.
func (fu *FollowUpdate) Mutation() *FollowMutation {
	return fu.mutation
}

// ClearFollower clears all "follower" edges to the User entity.
func (fu *FollowUpdate) ClearFollower() *FollowUpdate {
	fu.mutation.ClearFollower()
	return fu
}

// RemoveFollowerIDs removes the "follower" edge to User entities by IDs.
func (fu *FollowUpdate) RemoveFollowerIDs(ids ...int) *FollowUpdate {
	fu.mutation.RemoveFollowerIDs(ids...)
	return fu
}

// RemoveFollower removes "follower" edges to User entities.
func (fu *FollowUpdate) RemoveFollower(u ...*User) *FollowUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fu.RemoveFollowerIDs(ids...)
}

// ClearFollowing clears all "following" edges to the User entity.
func (fu *FollowUpdate) ClearFollowing() *FollowUpdate {
	fu.mutation.ClearFollowing()
	return fu
}

// RemoveFollowingIDs removes the "following" edge to User entities by IDs.
func (fu *FollowUpdate) RemoveFollowingIDs(ids ...int) *FollowUpdate {
	fu.mutation.RemoveFollowingIDs(ids...)
	return fu
}

// RemoveFollowing removes "following" edges to User entities.
func (fu *FollowUpdate) RemoveFollowing(u ...*User) *FollowUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fu.RemoveFollowingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FollowUpdate) Save(ctx context.Context) (int, error) {
	fu.defaults()
	return withHooks(ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FollowUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FollowUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FollowUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fu *FollowUpdate) defaults() {
	if _, ok := fu.mutation.UpdateTime(); !ok {
		v := follow.UpdateDefaultUpdateTime()
		fu.mutation.SetUpdateTime(v)
	}
}

func (fu *FollowUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(follow.Table, follow.Columns, sqlgraph.NewFieldSpec(follow.FieldID, field.TypeInt))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.UpdateTime(); ok {
		_spec.SetField(follow.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := fu.mutation.FollowerID(); ok {
		_spec.SetField(follow.FieldFollowerID, field.TypeInt, value)
	}
	if value, ok := fu.mutation.AddedFollowerID(); ok {
		_spec.AddField(follow.FieldFollowerID, field.TypeInt, value)
	}
	if value, ok := fu.mutation.FollowingID(); ok {
		_spec.SetField(follow.FieldFollowingID, field.TypeInt, value)
	}
	if value, ok := fu.mutation.AddedFollowingID(); ok {
		_spec.AddField(follow.FieldFollowingID, field.TypeInt, value)
	}
	if fu.mutation.FollowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.RemovedFollowerIDs(); len(nodes) > 0 && !fu.mutation.FollowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.FollowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fu.mutation.FollowingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.RemovedFollowingIDs(); len(nodes) > 0 && !fu.mutation.FollowingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.FollowingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FollowUpdateOne is the builder for updating a single Follow entity.
type FollowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FollowMutation
}

// SetUpdateTime sets the "update_time" field.
func (fuo *FollowUpdateOne) SetUpdateTime(t time.Time) *FollowUpdateOne {
	fuo.mutation.SetUpdateTime(t)
	return fuo
}

// SetFollowerID sets the "follower_id" field.
func (fuo *FollowUpdateOne) SetFollowerID(i int) *FollowUpdateOne {
	fuo.mutation.ResetFollowerID()
	fuo.mutation.SetFollowerID(i)
	return fuo
}

// SetNillableFollowerID sets the "follower_id" field if the given value is not nil.
func (fuo *FollowUpdateOne) SetNillableFollowerID(i *int) *FollowUpdateOne {
	if i != nil {
		fuo.SetFollowerID(*i)
	}
	return fuo
}

// AddFollowerID adds i to the "follower_id" field.
func (fuo *FollowUpdateOne) AddFollowerID(i int) *FollowUpdateOne {
	fuo.mutation.AddFollowerID(i)
	return fuo
}

// SetFollowingID sets the "following_id" field.
func (fuo *FollowUpdateOne) SetFollowingID(i int) *FollowUpdateOne {
	fuo.mutation.ResetFollowingID()
	fuo.mutation.SetFollowingID(i)
	return fuo
}

// SetNillableFollowingID sets the "following_id" field if the given value is not nil.
func (fuo *FollowUpdateOne) SetNillableFollowingID(i *int) *FollowUpdateOne {
	if i != nil {
		fuo.SetFollowingID(*i)
	}
	return fuo
}

// AddFollowingID adds i to the "following_id" field.
func (fuo *FollowUpdateOne) AddFollowingID(i int) *FollowUpdateOne {
	fuo.mutation.AddFollowingID(i)
	return fuo
}

// AddFollowerIDs adds the "follower" edge to the User entity by IDs.
func (fuo *FollowUpdateOne) AddFollowerIDs(ids ...int) *FollowUpdateOne {
	fuo.mutation.AddFollowerIDs(ids...)
	return fuo
}

// AddFollower adds the "follower" edges to the User entity.
func (fuo *FollowUpdateOne) AddFollower(u ...*User) *FollowUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fuo.AddFollowerIDs(ids...)
}

// AddFollowingIDs adds the "following" edge to the User entity by IDs.
func (fuo *FollowUpdateOne) AddFollowingIDs(ids ...int) *FollowUpdateOne {
	fuo.mutation.AddFollowingIDs(ids...)
	return fuo
}

// AddFollowing adds the "following" edges to the User entity.
func (fuo *FollowUpdateOne) AddFollowing(u ...*User) *FollowUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fuo.AddFollowingIDs(ids...)
}

// Mutation returns the FollowMutation object of the builder.
func (fuo *FollowUpdateOne) Mutation() *FollowMutation {
	return fuo.mutation
}

// ClearFollower clears all "follower" edges to the User entity.
func (fuo *FollowUpdateOne) ClearFollower() *FollowUpdateOne {
	fuo.mutation.ClearFollower()
	return fuo
}

// RemoveFollowerIDs removes the "follower" edge to User entities by IDs.
func (fuo *FollowUpdateOne) RemoveFollowerIDs(ids ...int) *FollowUpdateOne {
	fuo.mutation.RemoveFollowerIDs(ids...)
	return fuo
}

// RemoveFollower removes "follower" edges to User entities.
func (fuo *FollowUpdateOne) RemoveFollower(u ...*User) *FollowUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fuo.RemoveFollowerIDs(ids...)
}

// ClearFollowing clears all "following" edges to the User entity.
func (fuo *FollowUpdateOne) ClearFollowing() *FollowUpdateOne {
	fuo.mutation.ClearFollowing()
	return fuo
}

// RemoveFollowingIDs removes the "following" edge to User entities by IDs.
func (fuo *FollowUpdateOne) RemoveFollowingIDs(ids ...int) *FollowUpdateOne {
	fuo.mutation.RemoveFollowingIDs(ids...)
	return fuo
}

// RemoveFollowing removes "following" edges to User entities.
func (fuo *FollowUpdateOne) RemoveFollowing(u ...*User) *FollowUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fuo.RemoveFollowingIDs(ids...)
}

// Where appends a list predicates to the FollowUpdate builder.
func (fuo *FollowUpdateOne) Where(ps ...predicate.Follow) *FollowUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FollowUpdateOne) Select(field string, fields ...string) *FollowUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Follow entity.
func (fuo *FollowUpdateOne) Save(ctx context.Context) (*Follow, error) {
	fuo.defaults()
	return withHooks(ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FollowUpdateOne) SaveX(ctx context.Context) *Follow {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FollowUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FollowUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fuo *FollowUpdateOne) defaults() {
	if _, ok := fuo.mutation.UpdateTime(); !ok {
		v := follow.UpdateDefaultUpdateTime()
		fuo.mutation.SetUpdateTime(v)
	}
}

func (fuo *FollowUpdateOne) sqlSave(ctx context.Context) (_node *Follow, err error) {
	_spec := sqlgraph.NewUpdateSpec(follow.Table, follow.Columns, sqlgraph.NewFieldSpec(follow.FieldID, field.TypeInt))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Follow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, follow.FieldID)
		for _, f := range fields {
			if !follow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != follow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.UpdateTime(); ok {
		_spec.SetField(follow.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.FollowerID(); ok {
		_spec.SetField(follow.FieldFollowerID, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.AddedFollowerID(); ok {
		_spec.AddField(follow.FieldFollowerID, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.FollowingID(); ok {
		_spec.SetField(follow.FieldFollowingID, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.AddedFollowingID(); ok {
		_spec.AddField(follow.FieldFollowingID, field.TypeInt, value)
	}
	if fuo.mutation.FollowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.RemovedFollowerIDs(); len(nodes) > 0 && !fuo.mutation.FollowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.FollowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fuo.mutation.FollowingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.RemovedFollowingIDs(); len(nodes) > 0 && !fuo.mutation.FollowingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.FollowingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Follow{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
