// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/posttag"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PostTag is the model entity for the PostTag schema.
type PostTag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID int `json:"post_id,omitempty"`
	// TagID holds the value of the "tag_id" field.
	TagID int `json:"tag_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostTagQuery when eager-loading is set.
	Edges        PostTagEdges `json:"edges"`
	post_tags    *int
	tag_posts    *int
	selectValues sql.SelectValues
}

// PostTagEdges holds the relations/edges for other nodes in the graph.
type PostTagEdges struct {
	// Post holds the value of the post edge.
	Post []*Post `json:"post,omitempty"`
	// Tag holds the value of the tag edge.
	Tag []*Tag `json:"tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading.
func (e PostTagEdges) PostOrErr() ([]*Post, error) {
	if e.loadedTypes[0] {
		return e.Post, nil
	}
	return nil, &NotLoadedError{edge: "post"}
}

// TagOrErr returns the Tag value or an error if the edge
// was not loaded in eager-loading.
func (e PostTagEdges) TagOrErr() ([]*Tag, error) {
	if e.loadedTypes[1] {
		return e.Tag, nil
	}
	return nil, &NotLoadedError{edge: "tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case posttag.FieldID, posttag.FieldPostID, posttag.FieldTagID:
			values[i] = new(sql.NullInt64)
		case posttag.ForeignKeys[0]: // post_tags
			values[i] = new(sql.NullInt64)
		case posttag.ForeignKeys[1]: // tag_posts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostTag fields.
func (pt *PostTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case posttag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pt.ID = int(value.Int64)
		case posttag.FieldPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				pt.PostID = int(value.Int64)
			}
		case posttag.FieldTagID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tag_id", values[i])
			} else if value.Valid {
				pt.TagID = int(value.Int64)
			}
		case posttag.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field post_tags", value)
			} else if value.Valid {
				pt.post_tags = new(int)
				*pt.post_tags = int(value.Int64)
			}
		case posttag.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tag_posts", value)
			} else if value.Valid {
				pt.tag_posts = new(int)
				*pt.tag_posts = int(value.Int64)
			}
		default:
			pt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostTag.
// This includes values selected through modifiers, order, etc.
func (pt *PostTag) Value(name string) (ent.Value, error) {
	return pt.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PostTag entity.
func (pt *PostTag) QueryPost() *PostQuery {
	return NewPostTagClient(pt.config).QueryPost(pt)
}

// QueryTag queries the "tag" edge of the PostTag entity.
func (pt *PostTag) QueryTag() *TagQuery {
	return NewPostTagClient(pt.config).QueryTag(pt)
}

// Update returns a builder for updating this PostTag.
// Note that you need to call PostTag.Unwrap() before calling this method if this PostTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (pt *PostTag) Update() *PostTagUpdateOne {
	return NewPostTagClient(pt.config).UpdateOne(pt)
}

// Unwrap unwraps the PostTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pt *PostTag) Unwrap() *PostTag {
	_tx, ok := pt.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostTag is not a transactional entity")
	}
	pt.config.driver = _tx.drv
	return pt
}

// String implements the fmt.Stringer.
func (pt *PostTag) String() string {
	var builder strings.Builder
	builder.WriteString("PostTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pt.ID))
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", pt.PostID))
	builder.WriteString(", ")
	builder.WriteString("tag_id=")
	builder.WriteString(fmt.Sprintf("%v", pt.TagID))
	builder.WriteByte(')')
	return builder.String()
}

// PostTags is a parsable slice of PostTag.
type PostTags []*PostTag
