// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/post"
	"backend/internal/ent/posttag"
	"backend/internal/ent/predicate"
	"backend/internal/ent/tag"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostTagUpdate is the builder for updating PostTag entities.
type PostTagUpdate struct {
	config
	hooks    []Hook
	mutation *PostTagMutation
}

// Where appends a list predicates to the PostTagUpdate builder.
func (ptu *PostTagUpdate) Where(ps ...predicate.PostTag) *PostTagUpdate {
	ptu.mutation.Where(ps...)
	return ptu
}

// SetPostID sets the "post_id" field.
func (ptu *PostTagUpdate) SetPostID(i int) *PostTagUpdate {
	ptu.mutation.ResetPostID()
	ptu.mutation.SetPostID(i)
	return ptu
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (ptu *PostTagUpdate) SetNillablePostID(i *int) *PostTagUpdate {
	if i != nil {
		ptu.SetPostID(*i)
	}
	return ptu
}

// AddPostID adds i to the "post_id" field.
func (ptu *PostTagUpdate) AddPostID(i int) *PostTagUpdate {
	ptu.mutation.AddPostID(i)
	return ptu
}

// SetTagID sets the "tag_id" field.
func (ptu *PostTagUpdate) SetTagID(i int) *PostTagUpdate {
	ptu.mutation.ResetTagID()
	ptu.mutation.SetTagID(i)
	return ptu
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (ptu *PostTagUpdate) SetNillableTagID(i *int) *PostTagUpdate {
	if i != nil {
		ptu.SetTagID(*i)
	}
	return ptu
}

// AddTagID adds i to the "tag_id" field.
func (ptu *PostTagUpdate) AddTagID(i int) *PostTagUpdate {
	ptu.mutation.AddTagID(i)
	return ptu
}

// AddPostIDs adds the "post" edge to the Post entity by IDs.
func (ptu *PostTagUpdate) AddPostIDs(ids ...int) *PostTagUpdate {
	ptu.mutation.AddPostIDs(ids...)
	return ptu
}

// AddPost adds the "post" edges to the Post entity.
func (ptu *PostTagUpdate) AddPost(p ...*Post) *PostTagUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptu.AddPostIDs(ids...)
}

// AddTagIDs adds the "tag" edge to the Tag entity by IDs.
func (ptu *PostTagUpdate) AddTagIDs(ids ...int) *PostTagUpdate {
	ptu.mutation.AddTagIDs(ids...)
	return ptu
}

// AddTag adds the "tag" edges to the Tag entity.
func (ptu *PostTagUpdate) AddTag(t ...*Tag) *PostTagUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ptu.AddTagIDs(ids...)
}

// Mutation returns the PostTagMutation object of the builder.
func (ptu *PostTagUpdate) Mutation() *PostTagMutation {
	return ptu.mutation
}

// ClearPost clears all "post" edges to the Post entity.
func (ptu *PostTagUpdate) ClearPost() *PostTagUpdate {
	ptu.mutation.ClearPost()
	return ptu
}

// RemovePostIDs removes the "post" edge to Post entities by IDs.
func (ptu *PostTagUpdate) RemovePostIDs(ids ...int) *PostTagUpdate {
	ptu.mutation.RemovePostIDs(ids...)
	return ptu
}

// RemovePost removes "post" edges to Post entities.
func (ptu *PostTagUpdate) RemovePost(p ...*Post) *PostTagUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptu.RemovePostIDs(ids...)
}

// ClearTag clears all "tag" edges to the Tag entity.
func (ptu *PostTagUpdate) ClearTag() *PostTagUpdate {
	ptu.mutation.ClearTag()
	return ptu
}

// RemoveTagIDs removes the "tag" edge to Tag entities by IDs.
func (ptu *PostTagUpdate) RemoveTagIDs(ids ...int) *PostTagUpdate {
	ptu.mutation.RemoveTagIDs(ids...)
	return ptu
}

// RemoveTag removes "tag" edges to Tag entities.
func (ptu *PostTagUpdate) RemoveTag(t ...*Tag) *PostTagUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ptu.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ptu *PostTagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ptu.sqlSave, ptu.mutation, ptu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ptu *PostTagUpdate) SaveX(ctx context.Context) int {
	affected, err := ptu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ptu *PostTagUpdate) Exec(ctx context.Context) error {
	_, err := ptu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptu *PostTagUpdate) ExecX(ctx context.Context) {
	if err := ptu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ptu *PostTagUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(posttag.Table, posttag.Columns, sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeInt))
	if ps := ptu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ptu.mutation.PostID(); ok {
		_spec.SetField(posttag.FieldPostID, field.TypeInt, value)
	}
	if value, ok := ptu.mutation.AddedPostID(); ok {
		_spec.AddField(posttag.FieldPostID, field.TypeInt, value)
	}
	if value, ok := ptu.mutation.TagID(); ok {
		_spec.SetField(posttag.FieldTagID, field.TypeInt, value)
	}
	if value, ok := ptu.mutation.AddedTagID(); ok {
		_spec.AddField(posttag.FieldTagID, field.TypeInt, value)
	}
	if ptu.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.PostTable,
			Columns: []string{posttag.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptu.mutation.RemovedPostIDs(); len(nodes) > 0 && !ptu.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.PostTable,
			Columns: []string{posttag.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptu.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.PostTable,
			Columns: []string{posttag.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ptu.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.TagTable,
			Columns: []string{posttag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptu.mutation.RemovedTagIDs(); len(nodes) > 0 && !ptu.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.TagTable,
			Columns: []string{posttag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptu.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.TagTable,
			Columns: []string{posttag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ptu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{posttag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ptu.mutation.done = true
	return n, nil
}

// PostTagUpdateOne is the builder for updating a single PostTag entity.
type PostTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostTagMutation
}

// SetPostID sets the "post_id" field.
func (ptuo *PostTagUpdateOne) SetPostID(i int) *PostTagUpdateOne {
	ptuo.mutation.ResetPostID()
	ptuo.mutation.SetPostID(i)
	return ptuo
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (ptuo *PostTagUpdateOne) SetNillablePostID(i *int) *PostTagUpdateOne {
	if i != nil {
		ptuo.SetPostID(*i)
	}
	return ptuo
}

// AddPostID adds i to the "post_id" field.
func (ptuo *PostTagUpdateOne) AddPostID(i int) *PostTagUpdateOne {
	ptuo.mutation.AddPostID(i)
	return ptuo
}

// SetTagID sets the "tag_id" field.
func (ptuo *PostTagUpdateOne) SetTagID(i int) *PostTagUpdateOne {
	ptuo.mutation.ResetTagID()
	ptuo.mutation.SetTagID(i)
	return ptuo
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (ptuo *PostTagUpdateOne) SetNillableTagID(i *int) *PostTagUpdateOne {
	if i != nil {
		ptuo.SetTagID(*i)
	}
	return ptuo
}

// AddTagID adds i to the "tag_id" field.
func (ptuo *PostTagUpdateOne) AddTagID(i int) *PostTagUpdateOne {
	ptuo.mutation.AddTagID(i)
	return ptuo
}

// AddPostIDs adds the "post" edge to the Post entity by IDs.
func (ptuo *PostTagUpdateOne) AddPostIDs(ids ...int) *PostTagUpdateOne {
	ptuo.mutation.AddPostIDs(ids...)
	return ptuo
}

// AddPost adds the "post" edges to the Post entity.
func (ptuo *PostTagUpdateOne) AddPost(p ...*Post) *PostTagUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptuo.AddPostIDs(ids...)
}

// AddTagIDs adds the "tag" edge to the Tag entity by IDs.
func (ptuo *PostTagUpdateOne) AddTagIDs(ids ...int) *PostTagUpdateOne {
	ptuo.mutation.AddTagIDs(ids...)
	return ptuo
}

// AddTag adds the "tag" edges to the Tag entity.
func (ptuo *PostTagUpdateOne) AddTag(t ...*Tag) *PostTagUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ptuo.AddTagIDs(ids...)
}

// Mutation returns the PostTagMutation object of the builder.
func (ptuo *PostTagUpdateOne) Mutation() *PostTagMutation {
	return ptuo.mutation
}

// ClearPost clears all "post" edges to the Post entity.
func (ptuo *PostTagUpdateOne) ClearPost() *PostTagUpdateOne {
	ptuo.mutation.ClearPost()
	return ptuo
}

// RemovePostIDs removes the "post" edge to Post entities by IDs.
func (ptuo *PostTagUpdateOne) RemovePostIDs(ids ...int) *PostTagUpdateOne {
	ptuo.mutation.RemovePostIDs(ids...)
	return ptuo
}

// RemovePost removes "post" edges to Post entities.
func (ptuo *PostTagUpdateOne) RemovePost(p ...*Post) *PostTagUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptuo.RemovePostIDs(ids...)
}

// ClearTag clears all "tag" edges to the Tag entity.
func (ptuo *PostTagUpdateOne) ClearTag() *PostTagUpdateOne {
	ptuo.mutation.ClearTag()
	return ptuo
}

// RemoveTagIDs removes the "tag" edge to Tag entities by IDs.
func (ptuo *PostTagUpdateOne) RemoveTagIDs(ids ...int) *PostTagUpdateOne {
	ptuo.mutation.RemoveTagIDs(ids...)
	return ptuo
}

// RemoveTag removes "tag" edges to Tag entities.
func (ptuo *PostTagUpdateOne) RemoveTag(t ...*Tag) *PostTagUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ptuo.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the PostTagUpdate builder.
func (ptuo *PostTagUpdateOne) Where(ps ...predicate.PostTag) *PostTagUpdateOne {
	ptuo.mutation.Where(ps...)
	return ptuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ptuo *PostTagUpdateOne) Select(field string, fields ...string) *PostTagUpdateOne {
	ptuo.fields = append([]string{field}, fields...)
	return ptuo
}

// Save executes the query and returns the updated PostTag entity.
func (ptuo *PostTagUpdateOne) Save(ctx context.Context) (*PostTag, error) {
	return withHooks(ctx, ptuo.sqlSave, ptuo.mutation, ptuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ptuo *PostTagUpdateOne) SaveX(ctx context.Context) *PostTag {
	node, err := ptuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ptuo *PostTagUpdateOne) Exec(ctx context.Context) error {
	_, err := ptuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptuo *PostTagUpdateOne) ExecX(ctx context.Context) {
	if err := ptuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ptuo *PostTagUpdateOne) sqlSave(ctx context.Context) (_node *PostTag, err error) {
	_spec := sqlgraph.NewUpdateSpec(posttag.Table, posttag.Columns, sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeInt))
	id, ok := ptuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ptuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, posttag.FieldID)
		for _, f := range fields {
			if !posttag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != posttag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ptuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ptuo.mutation.PostID(); ok {
		_spec.SetField(posttag.FieldPostID, field.TypeInt, value)
	}
	if value, ok := ptuo.mutation.AddedPostID(); ok {
		_spec.AddField(posttag.FieldPostID, field.TypeInt, value)
	}
	if value, ok := ptuo.mutation.TagID(); ok {
		_spec.SetField(posttag.FieldTagID, field.TypeInt, value)
	}
	if value, ok := ptuo.mutation.AddedTagID(); ok {
		_spec.AddField(posttag.FieldTagID, field.TypeInt, value)
	}
	if ptuo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.PostTable,
			Columns: []string{posttag.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptuo.mutation.RemovedPostIDs(); len(nodes) > 0 && !ptuo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.PostTable,
			Columns: []string{posttag.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptuo.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.PostTable,
			Columns: []string{posttag.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ptuo.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.TagTable,
			Columns: []string{posttag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptuo.mutation.RemovedTagIDs(); len(nodes) > 0 && !ptuo.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.TagTable,
			Columns: []string{posttag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptuo.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.TagTable,
			Columns: []string{posttag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PostTag{config: ptuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ptuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{posttag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ptuo.mutation.done = true
	return _node, nil
}
