// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/post"
	"backend/internal/ent/posttag"
	"backend/internal/ent/tag"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostTagCreate is the builder for creating a PostTag entity.
type PostTagCreate struct {
	config
	mutation *PostTagMutation
	hooks    []Hook
}

// SetPostID sets the "post_id" field.
func (ptc *PostTagCreate) SetPostID(i int) *PostTagCreate {
	ptc.mutation.SetPostID(i)
	return ptc
}

// SetTagID sets the "tag_id" field.
func (ptc *PostTagCreate) SetTagID(i int) *PostTagCreate {
	ptc.mutation.SetTagID(i)
	return ptc
}

// AddPostIDs adds the "post" edge to the Post entity by IDs.
func (ptc *PostTagCreate) AddPostIDs(ids ...int) *PostTagCreate {
	ptc.mutation.AddPostIDs(ids...)
	return ptc
}

// AddPost adds the "post" edges to the Post entity.
func (ptc *PostTagCreate) AddPost(p ...*Post) *PostTagCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ptc.AddPostIDs(ids...)
}

// AddTagIDs adds the "tag" edge to the Tag entity by IDs.
func (ptc *PostTagCreate) AddTagIDs(ids ...int) *PostTagCreate {
	ptc.mutation.AddTagIDs(ids...)
	return ptc
}

// AddTag adds the "tag" edges to the Tag entity.
func (ptc *PostTagCreate) AddTag(t ...*Tag) *PostTagCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ptc.AddTagIDs(ids...)
}

// Mutation returns the PostTagMutation object of the builder.
func (ptc *PostTagCreate) Mutation() *PostTagMutation {
	return ptc.mutation
}

// Save creates the PostTag in the database.
func (ptc *PostTagCreate) Save(ctx context.Context) (*PostTag, error) {
	return withHooks(ctx, ptc.sqlSave, ptc.mutation, ptc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ptc *PostTagCreate) SaveX(ctx context.Context) *PostTag {
	v, err := ptc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ptc *PostTagCreate) Exec(ctx context.Context) error {
	_, err := ptc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptc *PostTagCreate) ExecX(ctx context.Context) {
	if err := ptc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ptc *PostTagCreate) check() error {
	if _, ok := ptc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PostTag.post_id"`)}
	}
	if _, ok := ptc.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "PostTag.tag_id"`)}
	}
	return nil
}

func (ptc *PostTagCreate) sqlSave(ctx context.Context) (*PostTag, error) {
	if err := ptc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ptc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ptc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ptc.mutation.id = &_node.ID
	ptc.mutation.done = true
	return _node, nil
}

func (ptc *PostTagCreate) createSpec() (*PostTag, *sqlgraph.CreateSpec) {
	var (
		_node = &PostTag{config: ptc.config}
		_spec = sqlgraph.NewCreateSpec(posttag.Table, sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeInt))
	)
	if value, ok := ptc.mutation.PostID(); ok {
		_spec.SetField(posttag.FieldPostID, field.TypeInt, value)
		_node.PostID = value
	}
	if value, ok := ptc.mutation.TagID(); ok {
		_spec.SetField(posttag.FieldTagID, field.TypeInt, value)
		_node.TagID = value
	}
	if nodes := ptc.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.PostTable,
			Columns: []string{posttag.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ptc.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   posttag.TagTable,
			Columns: []string{posttag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostTagCreateBulk is the builder for creating many PostTag entities in bulk.
type PostTagCreateBulk struct {
	config
	err      error
	builders []*PostTagCreate
}

// Save creates the PostTag entities in the database.
func (ptcb *PostTagCreateBulk) Save(ctx context.Context) ([]*PostTag, error) {
	if ptcb.err != nil {
		return nil, ptcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ptcb.builders))
	nodes := make([]*PostTag, len(ptcb.builders))
	mutators := make([]Mutator, len(ptcb.builders))
	for i := range ptcb.builders {
		func(i int, root context.Context) {
			builder := ptcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ptcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ptcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ptcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ptcb *PostTagCreateBulk) SaveX(ctx context.Context) []*PostTag {
	v, err := ptcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ptcb *PostTagCreateBulk) Exec(ctx context.Context) error {
	_, err := ptcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptcb *PostTagCreateBulk) ExecX(ctx context.Context) {
	if err := ptcb.Exec(ctx); err != nil {
		panic(err)
	}
}
