// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/predicate"
	"backend/internal/ent/question"
	"backend/internal/ent/questiontag"
	"backend/internal/ent/tag"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionTagUpdate is the builder for updating QuestionTag entities.
type QuestionTagUpdate struct {
	config
	hooks    []Hook
	mutation *QuestionTagMutation
}

// Where appends a list predicates to the QuestionTagUpdate builder.
func (qtu *QuestionTagUpdate) Where(ps ...predicate.QuestionTag) *QuestionTagUpdate {
	qtu.mutation.Where(ps...)
	return qtu
}

// SetQuestionID sets the "question_id" field.
func (qtu *QuestionTagUpdate) SetQuestionID(i int) *QuestionTagUpdate {
	qtu.mutation.ResetQuestionID()
	qtu.mutation.SetQuestionID(i)
	return qtu
}

// SetNillableQuestionID sets the "question_id" field if the given value is not nil.
func (qtu *QuestionTagUpdate) SetNillableQuestionID(i *int) *QuestionTagUpdate {
	if i != nil {
		qtu.SetQuestionID(*i)
	}
	return qtu
}

// AddQuestionID adds i to the "question_id" field.
func (qtu *QuestionTagUpdate) AddQuestionID(i int) *QuestionTagUpdate {
	qtu.mutation.AddQuestionID(i)
	return qtu
}

// SetTagID sets the "tag_id" field.
func (qtu *QuestionTagUpdate) SetTagID(i int) *QuestionTagUpdate {
	qtu.mutation.ResetTagID()
	qtu.mutation.SetTagID(i)
	return qtu
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (qtu *QuestionTagUpdate) SetNillableTagID(i *int) *QuestionTagUpdate {
	if i != nil {
		qtu.SetTagID(*i)
	}
	return qtu
}

// AddTagID adds i to the "tag_id" field.
func (qtu *QuestionTagUpdate) AddTagID(i int) *QuestionTagUpdate {
	qtu.mutation.AddTagID(i)
	return qtu
}

// AddQuestionIDs adds the "question" edge to the Question entity by IDs.
func (qtu *QuestionTagUpdate) AddQuestionIDs(ids ...int) *QuestionTagUpdate {
	qtu.mutation.AddQuestionIDs(ids...)
	return qtu
}

// AddQuestion adds the "question" edges to the Question entity.
func (qtu *QuestionTagUpdate) AddQuestion(q ...*Question) *QuestionTagUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return qtu.AddQuestionIDs(ids...)
}

// AddTagIDs adds the "tag" edge to the Tag entity by IDs.
func (qtu *QuestionTagUpdate) AddTagIDs(ids ...int) *QuestionTagUpdate {
	qtu.mutation.AddTagIDs(ids...)
	return qtu
}

// AddTag adds the "tag" edges to the Tag entity.
func (qtu *QuestionTagUpdate) AddTag(t ...*Tag) *QuestionTagUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return qtu.AddTagIDs(ids...)
}

// Mutation returns the QuestionTagMutation object of the builder.
func (qtu *QuestionTagUpdate) Mutation() *QuestionTagMutation {
	return qtu.mutation
}

// ClearQuestion clears all "question" edges to the Question entity.
func (qtu *QuestionTagUpdate) ClearQuestion() *QuestionTagUpdate {
	qtu.mutation.ClearQuestion()
	return qtu
}

// RemoveQuestionIDs removes the "question" edge to Question entities by IDs.
func (qtu *QuestionTagUpdate) RemoveQuestionIDs(ids ...int) *QuestionTagUpdate {
	qtu.mutation.RemoveQuestionIDs(ids...)
	return qtu
}

// RemoveQuestion removes "question" edges to Question entities.
func (qtu *QuestionTagUpdate) RemoveQuestion(q ...*Question) *QuestionTagUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return qtu.RemoveQuestionIDs(ids...)
}

// ClearTag clears all "tag" edges to the Tag entity.
func (qtu *QuestionTagUpdate) ClearTag() *QuestionTagUpdate {
	qtu.mutation.ClearTag()
	return qtu
}

// RemoveTagIDs removes the "tag" edge to Tag entities by IDs.
func (qtu *QuestionTagUpdate) RemoveTagIDs(ids ...int) *QuestionTagUpdate {
	qtu.mutation.RemoveTagIDs(ids...)
	return qtu
}

// RemoveTag removes "tag" edges to Tag entities.
func (qtu *QuestionTagUpdate) RemoveTag(t ...*Tag) *QuestionTagUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return qtu.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (qtu *QuestionTagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, qtu.sqlSave, qtu.mutation, qtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (qtu *QuestionTagUpdate) SaveX(ctx context.Context) int {
	affected, err := qtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (qtu *QuestionTagUpdate) Exec(ctx context.Context) error {
	_, err := qtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qtu *QuestionTagUpdate) ExecX(ctx context.Context) {
	if err := qtu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (qtu *QuestionTagUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(questiontag.Table, questiontag.Columns, sqlgraph.NewFieldSpec(questiontag.FieldID, field.TypeInt))
	if ps := qtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := qtu.mutation.QuestionID(); ok {
		_spec.SetField(questiontag.FieldQuestionID, field.TypeInt, value)
	}
	if value, ok := qtu.mutation.AddedQuestionID(); ok {
		_spec.AddField(questiontag.FieldQuestionID, field.TypeInt, value)
	}
	if value, ok := qtu.mutation.TagID(); ok {
		_spec.SetField(questiontag.FieldTagID, field.TypeInt, value)
	}
	if value, ok := qtu.mutation.AddedTagID(); ok {
		_spec.AddField(questiontag.FieldTagID, field.TypeInt, value)
	}
	if qtu.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.QuestionTable,
			Columns: []string{questiontag.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qtu.mutation.RemovedQuestionIDs(); len(nodes) > 0 && !qtu.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.QuestionTable,
			Columns: []string{questiontag.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qtu.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.QuestionTable,
			Columns: []string{questiontag.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if qtu.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.TagTable,
			Columns: []string{questiontag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qtu.mutation.RemovedTagIDs(); len(nodes) > 0 && !qtu.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.TagTable,
			Columns: []string{questiontag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qtu.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.TagTable,
			Columns: []string{questiontag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, qtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{questiontag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	qtu.mutation.done = true
	return n, nil
}

// QuestionTagUpdateOne is the builder for updating a single QuestionTag entity.
type QuestionTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuestionTagMutation
}

// SetQuestionID sets the "question_id" field.
func (qtuo *QuestionTagUpdateOne) SetQuestionID(i int) *QuestionTagUpdateOne {
	qtuo.mutation.ResetQuestionID()
	qtuo.mutation.SetQuestionID(i)
	return qtuo
}

// SetNillableQuestionID sets the "question_id" field if the given value is not nil.
func (qtuo *QuestionTagUpdateOne) SetNillableQuestionID(i *int) *QuestionTagUpdateOne {
	if i != nil {
		qtuo.SetQuestionID(*i)
	}
	return qtuo
}

// AddQuestionID adds i to the "question_id" field.
func (qtuo *QuestionTagUpdateOne) AddQuestionID(i int) *QuestionTagUpdateOne {
	qtuo.mutation.AddQuestionID(i)
	return qtuo
}

// SetTagID sets the "tag_id" field.
func (qtuo *QuestionTagUpdateOne) SetTagID(i int) *QuestionTagUpdateOne {
	qtuo.mutation.ResetTagID()
	qtuo.mutation.SetTagID(i)
	return qtuo
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (qtuo *QuestionTagUpdateOne) SetNillableTagID(i *int) *QuestionTagUpdateOne {
	if i != nil {
		qtuo.SetTagID(*i)
	}
	return qtuo
}

// AddTagID adds i to the "tag_id" field.
func (qtuo *QuestionTagUpdateOne) AddTagID(i int) *QuestionTagUpdateOne {
	qtuo.mutation.AddTagID(i)
	return qtuo
}

// AddQuestionIDs adds the "question" edge to the Question entity by IDs.
func (qtuo *QuestionTagUpdateOne) AddQuestionIDs(ids ...int) *QuestionTagUpdateOne {
	qtuo.mutation.AddQuestionIDs(ids...)
	return qtuo
}

// AddQuestion adds the "question" edges to the Question entity.
func (qtuo *QuestionTagUpdateOne) AddQuestion(q ...*Question) *QuestionTagUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return qtuo.AddQuestionIDs(ids...)
}

// AddTagIDs adds the "tag" edge to the Tag entity by IDs.
func (qtuo *QuestionTagUpdateOne) AddTagIDs(ids ...int) *QuestionTagUpdateOne {
	qtuo.mutation.AddTagIDs(ids...)
	return qtuo
}

// AddTag adds the "tag" edges to the Tag entity.
func (qtuo *QuestionTagUpdateOne) AddTag(t ...*Tag) *QuestionTagUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return qtuo.AddTagIDs(ids...)
}

// Mutation returns the QuestionTagMutation object of the builder.
func (qtuo *QuestionTagUpdateOne) Mutation() *QuestionTagMutation {
	return qtuo.mutation
}

// ClearQuestion clears all "question" edges to the Question entity.
func (qtuo *QuestionTagUpdateOne) ClearQuestion() *QuestionTagUpdateOne {
	qtuo.mutation.ClearQuestion()
	return qtuo
}

// RemoveQuestionIDs removes the "question" edge to Question entities by IDs.
func (qtuo *QuestionTagUpdateOne) RemoveQuestionIDs(ids ...int) *QuestionTagUpdateOne {
	qtuo.mutation.RemoveQuestionIDs(ids...)
	return qtuo
}

// RemoveQuestion removes "question" edges to Question entities.
func (qtuo *QuestionTagUpdateOne) RemoveQuestion(q ...*Question) *QuestionTagUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return qtuo.RemoveQuestionIDs(ids...)
}

// ClearTag clears all "tag" edges to the Tag entity.
func (qtuo *QuestionTagUpdateOne) ClearTag() *QuestionTagUpdateOne {
	qtuo.mutation.ClearTag()
	return qtuo
}

// RemoveTagIDs removes the "tag" edge to Tag entities by IDs.
func (qtuo *QuestionTagUpdateOne) RemoveTagIDs(ids ...int) *QuestionTagUpdateOne {
	qtuo.mutation.RemoveTagIDs(ids...)
	return qtuo
}

// RemoveTag removes "tag" edges to Tag entities.
func (qtuo *QuestionTagUpdateOne) RemoveTag(t ...*Tag) *QuestionTagUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return qtuo.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the QuestionTagUpdate builder.
func (qtuo *QuestionTagUpdateOne) Where(ps ...predicate.QuestionTag) *QuestionTagUpdateOne {
	qtuo.mutation.Where(ps...)
	return qtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (qtuo *QuestionTagUpdateOne) Select(field string, fields ...string) *QuestionTagUpdateOne {
	qtuo.fields = append([]string{field}, fields...)
	return qtuo
}

// Save executes the query and returns the updated QuestionTag entity.
func (qtuo *QuestionTagUpdateOne) Save(ctx context.Context) (*QuestionTag, error) {
	return withHooks(ctx, qtuo.sqlSave, qtuo.mutation, qtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (qtuo *QuestionTagUpdateOne) SaveX(ctx context.Context) *QuestionTag {
	node, err := qtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (qtuo *QuestionTagUpdateOne) Exec(ctx context.Context) error {
	_, err := qtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qtuo *QuestionTagUpdateOne) ExecX(ctx context.Context) {
	if err := qtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (qtuo *QuestionTagUpdateOne) sqlSave(ctx context.Context) (_node *QuestionTag, err error) {
	_spec := sqlgraph.NewUpdateSpec(questiontag.Table, questiontag.Columns, sqlgraph.NewFieldSpec(questiontag.FieldID, field.TypeInt))
	id, ok := qtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuestionTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := qtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, questiontag.FieldID)
		for _, f := range fields {
			if !questiontag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != questiontag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := qtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := qtuo.mutation.QuestionID(); ok {
		_spec.SetField(questiontag.FieldQuestionID, field.TypeInt, value)
	}
	if value, ok := qtuo.mutation.AddedQuestionID(); ok {
		_spec.AddField(questiontag.FieldQuestionID, field.TypeInt, value)
	}
	if value, ok := qtuo.mutation.TagID(); ok {
		_spec.SetField(questiontag.FieldTagID, field.TypeInt, value)
	}
	if value, ok := qtuo.mutation.AddedTagID(); ok {
		_spec.AddField(questiontag.FieldTagID, field.TypeInt, value)
	}
	if qtuo.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.QuestionTable,
			Columns: []string{questiontag.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qtuo.mutation.RemovedQuestionIDs(); len(nodes) > 0 && !qtuo.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.QuestionTable,
			Columns: []string{questiontag.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qtuo.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.QuestionTable,
			Columns: []string{questiontag.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if qtuo.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.TagTable,
			Columns: []string{questiontag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qtuo.mutation.RemovedTagIDs(); len(nodes) > 0 && !qtuo.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.TagTable,
			Columns: []string{questiontag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qtuo.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questiontag.TagTable,
			Columns: []string{questiontag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &QuestionTag{config: qtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, qtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{questiontag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	qtuo.mutation.done = true
	return _node, nil
}
