// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/comment"
	"backend/internal/ent/predicate"
	"backend/internal/ent/question"
	"backend/internal/ent/questiontag"
	"backend/internal/ent/user"
	"backend/internal/ent/userfavoritequestion"
	"backend/internal/ent/userlikequestion"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionUpdate is the builder for updating Question entities.
type QuestionUpdate struct {
	config
	hooks    []Hook
	mutation *QuestionMutation
}

// Where appends a list predicates to the QuestionUpdate builder.
func (qu *QuestionUpdate) Where(ps ...predicate.Question) *QuestionUpdate {
	qu.mutation.Where(ps...)
	return qu
}

// SetUpdateTime sets the "update_time" field.
func (qu *QuestionUpdate) SetUpdateTime(t time.Time) *QuestionUpdate {
	qu.mutation.SetUpdateTime(t)
	return qu
}

// SetTitle sets the "title" field.
func (qu *QuestionUpdate) SetTitle(s string) *QuestionUpdate {
	qu.mutation.SetTitle(s)
	return qu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableTitle(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetTitle(*s)
	}
	return qu
}

// SetEmbedding sets the "embedding" field.
func (qu *QuestionUpdate) SetEmbedding(b []byte) *QuestionUpdate {
	qu.mutation.SetEmbedding(b)
	return qu
}

// ClearEmbedding clears the value of the "embedding" field.
func (qu *QuestionUpdate) ClearEmbedding() *QuestionUpdate {
	qu.mutation.ClearEmbedding()
	return qu
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (qu *QuestionUpdate) AddUserIDs(ids ...int) *QuestionUpdate {
	qu.mutation.AddUserIDs(ids...)
	return qu
}

// AddUser adds the "user" edges to the User entity.
func (qu *QuestionUpdate) AddUser(u ...*User) *QuestionUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return qu.AddUserIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (qu *QuestionUpdate) AddCommentIDs(ids ...int) *QuestionUpdate {
	qu.mutation.AddCommentIDs(ids...)
	return qu
}

// AddComments adds the "comments" edges to the Comment entity.
func (qu *QuestionUpdate) AddComments(c ...*Comment) *QuestionUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return qu.AddCommentIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the QuestionTag entity by IDs.
func (qu *QuestionUpdate) AddTagIDs(ids ...int) *QuestionUpdate {
	qu.mutation.AddTagIDs(ids...)
	return qu
}

// AddTags adds the "tags" edges to the QuestionTag entity.
func (qu *QuestionUpdate) AddTags(q ...*QuestionTag) *QuestionUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return qu.AddTagIDs(ids...)
}

// AddLikeIDs adds the "likes" edge to the UserLikeQuestion entity by IDs.
func (qu *QuestionUpdate) AddLikeIDs(ids ...int) *QuestionUpdate {
	qu.mutation.AddLikeIDs(ids...)
	return qu
}

// AddLikes adds the "likes" edges to the UserLikeQuestion entity.
func (qu *QuestionUpdate) AddLikes(u ...*UserLikeQuestion) *QuestionUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return qu.AddLikeIDs(ids...)
}

// AddFavoriteIDs adds the "favorites" edge to the UserFavoriteQuestion entity by IDs.
func (qu *QuestionUpdate) AddFavoriteIDs(ids ...int) *QuestionUpdate {
	qu.mutation.AddFavoriteIDs(ids...)
	return qu
}

// AddFavorites adds the "favorites" edges to the UserFavoriteQuestion entity.
func (qu *QuestionUpdate) AddFavorites(u ...*UserFavoriteQuestion) *QuestionUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return qu.AddFavoriteIDs(ids...)
}

// Mutation returns the QuestionMutation object of the builder.
func (qu *QuestionUpdate) Mutation() *QuestionMutation {
	return qu.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (qu *QuestionUpdate) ClearUser() *QuestionUpdate {
	qu.mutation.ClearUser()
	return qu
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (qu *QuestionUpdate) RemoveUserIDs(ids ...int) *QuestionUpdate {
	qu.mutation.RemoveUserIDs(ids...)
	return qu
}

// RemoveUser removes "user" edges to User entities.
func (qu *QuestionUpdate) RemoveUser(u ...*User) *QuestionUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return qu.RemoveUserIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (qu *QuestionUpdate) ClearComments() *QuestionUpdate {
	qu.mutation.ClearComments()
	return qu
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (qu *QuestionUpdate) RemoveCommentIDs(ids ...int) *QuestionUpdate {
	qu.mutation.RemoveCommentIDs(ids...)
	return qu
}

// RemoveComments removes "comments" edges to Comment entities.
func (qu *QuestionUpdate) RemoveComments(c ...*Comment) *QuestionUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return qu.RemoveCommentIDs(ids...)
}

// ClearTags clears all "tags" edges to the QuestionTag entity.
func (qu *QuestionUpdate) ClearTags() *QuestionUpdate {
	qu.mutation.ClearTags()
	return qu
}

// RemoveTagIDs removes the "tags" edge to QuestionTag entities by IDs.
func (qu *QuestionUpdate) RemoveTagIDs(ids ...int) *QuestionUpdate {
	qu.mutation.RemoveTagIDs(ids...)
	return qu
}

// RemoveTags removes "tags" edges to QuestionTag entities.
func (qu *QuestionUpdate) RemoveTags(q ...*QuestionTag) *QuestionUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return qu.RemoveTagIDs(ids...)
}

// ClearLikes clears all "likes" edges to the UserLikeQuestion entity.
func (qu *QuestionUpdate) ClearLikes() *QuestionUpdate {
	qu.mutation.ClearLikes()
	return qu
}

// RemoveLikeIDs removes the "likes" edge to UserLikeQuestion entities by IDs.
func (qu *QuestionUpdate) RemoveLikeIDs(ids ...int) *QuestionUpdate {
	qu.mutation.RemoveLikeIDs(ids...)
	return qu
}

// RemoveLikes removes "likes" edges to UserLikeQuestion entities.
func (qu *QuestionUpdate) RemoveLikes(u ...*UserLikeQuestion) *QuestionUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return qu.RemoveLikeIDs(ids...)
}

// ClearFavorites clears all "favorites" edges to the UserFavoriteQuestion entity.
func (qu *QuestionUpdate) ClearFavorites() *QuestionUpdate {
	qu.mutation.ClearFavorites()
	return qu
}

// RemoveFavoriteIDs removes the "favorites" edge to UserFavoriteQuestion entities by IDs.
func (qu *QuestionUpdate) RemoveFavoriteIDs(ids ...int) *QuestionUpdate {
	qu.mutation.RemoveFavoriteIDs(ids...)
	return qu
}

// RemoveFavorites removes "favorites" edges to UserFavoriteQuestion entities.
func (qu *QuestionUpdate) RemoveFavorites(u ...*UserFavoriteQuestion) *QuestionUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return qu.RemoveFavoriteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (qu *QuestionUpdate) Save(ctx context.Context) (int, error) {
	qu.defaults()
	return withHooks(ctx, qu.sqlSave, qu.mutation, qu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (qu *QuestionUpdate) SaveX(ctx context.Context) int {
	affected, err := qu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (qu *QuestionUpdate) Exec(ctx context.Context) error {
	_, err := qu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qu *QuestionUpdate) ExecX(ctx context.Context) {
	if err := qu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qu *QuestionUpdate) defaults() {
	if _, ok := qu.mutation.UpdateTime(); !ok {
		v := question.UpdateDefaultUpdateTime()
		qu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qu *QuestionUpdate) check() error {
	if v, ok := qu.mutation.Title(); ok {
		if err := question.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Question.title": %w`, err)}
		}
	}
	return nil
}

func (qu *QuestionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := qu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt))
	if ps := qu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := qu.mutation.UpdateTime(); ok {
		_spec.SetField(question.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := qu.mutation.Title(); ok {
		_spec.SetField(question.FieldTitle, field.TypeString, value)
	}
	if value, ok := qu.mutation.Embedding(); ok {
		_spec.SetField(question.FieldEmbedding, field.TypeBytes, value)
	}
	if qu.mutation.EmbeddingCleared() {
		_spec.ClearField(question.FieldEmbedding, field.TypeBytes)
	}
	if qu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.UserTable,
			Columns: []string{question.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.RemovedUserIDs(); len(nodes) > 0 && !qu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.UserTable,
			Columns: []string{question.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.UserTable,
			Columns: []string{question.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if qu.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.CommentsTable,
			Columns: []string{question.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !qu.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.CommentsTable,
			Columns: []string{question.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.CommentsTable,
			Columns: []string{question.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if qu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.TagsTable,
			Columns: []string{question.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questiontag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.RemovedTagsIDs(); len(nodes) > 0 && !qu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.TagsTable,
			Columns: []string{question.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questiontag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.TagsTable,
			Columns: []string{question.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questiontag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if qu.mutation.LikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.LikesTable,
			Columns: []string{question.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userlikequestion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.RemovedLikesIDs(); len(nodes) > 0 && !qu.mutation.LikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.LikesTable,
			Columns: []string{question.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userlikequestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.LikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.LikesTable,
			Columns: []string{question.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userlikequestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if qu.mutation.FavoritesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.FavoritesTable,
			Columns: []string{question.FavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfavoritequestion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.RemovedFavoritesIDs(); len(nodes) > 0 && !qu.mutation.FavoritesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.FavoritesTable,
			Columns: []string{question.FavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfavoritequestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.FavoritesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.FavoritesTable,
			Columns: []string{question.FavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfavoritequestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, qu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	qu.mutation.done = true
	return n, nil
}

// QuestionUpdateOne is the builder for updating a single Question entity.
type QuestionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuestionMutation
}

// SetUpdateTime sets the "update_time" field.
func (quo *QuestionUpdateOne) SetUpdateTime(t time.Time) *QuestionUpdateOne {
	quo.mutation.SetUpdateTime(t)
	return quo
}

// SetTitle sets the "title" field.
func (quo *QuestionUpdateOne) SetTitle(s string) *QuestionUpdateOne {
	quo.mutation.SetTitle(s)
	return quo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableTitle(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetTitle(*s)
	}
	return quo
}

// SetEmbedding sets the "embedding" field.
func (quo *QuestionUpdateOne) SetEmbedding(b []byte) *QuestionUpdateOne {
	quo.mutation.SetEmbedding(b)
	return quo
}

// ClearEmbedding clears the value of the "embedding" field.
func (quo *QuestionUpdateOne) ClearEmbedding() *QuestionUpdateOne {
	quo.mutation.ClearEmbedding()
	return quo
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (quo *QuestionUpdateOne) AddUserIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.AddUserIDs(ids...)
	return quo
}

// AddUser adds the "user" edges to the User entity.
func (quo *QuestionUpdateOne) AddUser(u ...*User) *QuestionUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return quo.AddUserIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (quo *QuestionUpdateOne) AddCommentIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.AddCommentIDs(ids...)
	return quo
}

// AddComments adds the "comments" edges to the Comment entity.
func (quo *QuestionUpdateOne) AddComments(c ...*Comment) *QuestionUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return quo.AddCommentIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the QuestionTag entity by IDs.
func (quo *QuestionUpdateOne) AddTagIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.AddTagIDs(ids...)
	return quo
}

// AddTags adds the "tags" edges to the QuestionTag entity.
func (quo *QuestionUpdateOne) AddTags(q ...*QuestionTag) *QuestionUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return quo.AddTagIDs(ids...)
}

// AddLikeIDs adds the "likes" edge to the UserLikeQuestion entity by IDs.
func (quo *QuestionUpdateOne) AddLikeIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.AddLikeIDs(ids...)
	return quo
}

// AddLikes adds the "likes" edges to the UserLikeQuestion entity.
func (quo *QuestionUpdateOne) AddLikes(u ...*UserLikeQuestion) *QuestionUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return quo.AddLikeIDs(ids...)
}

// AddFavoriteIDs adds the "favorites" edge to the UserFavoriteQuestion entity by IDs.
func (quo *QuestionUpdateOne) AddFavoriteIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.AddFavoriteIDs(ids...)
	return quo
}

// AddFavorites adds the "favorites" edges to the UserFavoriteQuestion entity.
func (quo *QuestionUpdateOne) AddFavorites(u ...*UserFavoriteQuestion) *QuestionUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return quo.AddFavoriteIDs(ids...)
}

// Mutation returns the QuestionMutation object of the builder.
func (quo *QuestionUpdateOne) Mutation() *QuestionMutation {
	return quo.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (quo *QuestionUpdateOne) ClearUser() *QuestionUpdateOne {
	quo.mutation.ClearUser()
	return quo
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (quo *QuestionUpdateOne) RemoveUserIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.RemoveUserIDs(ids...)
	return quo
}

// RemoveUser removes "user" edges to User entities.
func (quo *QuestionUpdateOne) RemoveUser(u ...*User) *QuestionUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return quo.RemoveUserIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (quo *QuestionUpdateOne) ClearComments() *QuestionUpdateOne {
	quo.mutation.ClearComments()
	return quo
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (quo *QuestionUpdateOne) RemoveCommentIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.RemoveCommentIDs(ids...)
	return quo
}

// RemoveComments removes "comments" edges to Comment entities.
func (quo *QuestionUpdateOne) RemoveComments(c ...*Comment) *QuestionUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return quo.RemoveCommentIDs(ids...)
}

// ClearTags clears all "tags" edges to the QuestionTag entity.
func (quo *QuestionUpdateOne) ClearTags() *QuestionUpdateOne {
	quo.mutation.ClearTags()
	return quo
}

// RemoveTagIDs removes the "tags" edge to QuestionTag entities by IDs.
func (quo *QuestionUpdateOne) RemoveTagIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.RemoveTagIDs(ids...)
	return quo
}

// RemoveTags removes "tags" edges to QuestionTag entities.
func (quo *QuestionUpdateOne) RemoveTags(q ...*QuestionTag) *QuestionUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return quo.RemoveTagIDs(ids...)
}

// ClearLikes clears all "likes" edges to the UserLikeQuestion entity.
func (quo *QuestionUpdateOne) ClearLikes() *QuestionUpdateOne {
	quo.mutation.ClearLikes()
	return quo
}

// RemoveLikeIDs removes the "likes" edge to UserLikeQuestion entities by IDs.
func (quo *QuestionUpdateOne) RemoveLikeIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.RemoveLikeIDs(ids...)
	return quo
}

// RemoveLikes removes "likes" edges to UserLikeQuestion entities.
func (quo *QuestionUpdateOne) RemoveLikes(u ...*UserLikeQuestion) *QuestionUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return quo.RemoveLikeIDs(ids...)
}

// ClearFavorites clears all "favorites" edges to the UserFavoriteQuestion entity.
func (quo *QuestionUpdateOne) ClearFavorites() *QuestionUpdateOne {
	quo.mutation.ClearFavorites()
	return quo
}

// RemoveFavoriteIDs removes the "favorites" edge to UserFavoriteQuestion entities by IDs.
func (quo *QuestionUpdateOne) RemoveFavoriteIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.RemoveFavoriteIDs(ids...)
	return quo
}

// RemoveFavorites removes "favorites" edges to UserFavoriteQuestion entities.
func (quo *QuestionUpdateOne) RemoveFavorites(u ...*UserFavoriteQuestion) *QuestionUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return quo.RemoveFavoriteIDs(ids...)
}

// Where appends a list predicates to the QuestionUpdate builder.
func (quo *QuestionUpdateOne) Where(ps ...predicate.Question) *QuestionUpdateOne {
	quo.mutation.Where(ps...)
	return quo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (quo *QuestionUpdateOne) Select(field string, fields ...string) *QuestionUpdateOne {
	quo.fields = append([]string{field}, fields...)
	return quo
}

// Save executes the query and returns the updated Question entity.
func (quo *QuestionUpdateOne) Save(ctx context.Context) (*Question, error) {
	quo.defaults()
	return withHooks(ctx, quo.sqlSave, quo.mutation, quo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (quo *QuestionUpdateOne) SaveX(ctx context.Context) *Question {
	node, err := quo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (quo *QuestionUpdateOne) Exec(ctx context.Context) error {
	_, err := quo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (quo *QuestionUpdateOne) ExecX(ctx context.Context) {
	if err := quo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (quo *QuestionUpdateOne) defaults() {
	if _, ok := quo.mutation.UpdateTime(); !ok {
		v := question.UpdateDefaultUpdateTime()
		quo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (quo *QuestionUpdateOne) check() error {
	if v, ok := quo.mutation.Title(); ok {
		if err := question.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Question.title": %w`, err)}
		}
	}
	return nil
}

func (quo *QuestionUpdateOne) sqlSave(ctx context.Context) (_node *Question, err error) {
	if err := quo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt))
	id, ok := quo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Question.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := quo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, question.FieldID)
		for _, f := range fields {
			if !question.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != question.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := quo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := quo.mutation.UpdateTime(); ok {
		_spec.SetField(question.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := quo.mutation.Title(); ok {
		_spec.SetField(question.FieldTitle, field.TypeString, value)
	}
	if value, ok := quo.mutation.Embedding(); ok {
		_spec.SetField(question.FieldEmbedding, field.TypeBytes, value)
	}
	if quo.mutation.EmbeddingCleared() {
		_spec.ClearField(question.FieldEmbedding, field.TypeBytes)
	}
	if quo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.UserTable,
			Columns: []string{question.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.RemovedUserIDs(); len(nodes) > 0 && !quo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.UserTable,
			Columns: []string{question.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.UserTable,
			Columns: []string{question.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if quo.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.CommentsTable,
			Columns: []string{question.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !quo.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.CommentsTable,
			Columns: []string{question.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.CommentsTable,
			Columns: []string{question.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if quo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.TagsTable,
			Columns: []string{question.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questiontag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.RemovedTagsIDs(); len(nodes) > 0 && !quo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.TagsTable,
			Columns: []string{question.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questiontag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.TagsTable,
			Columns: []string{question.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questiontag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if quo.mutation.LikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.LikesTable,
			Columns: []string{question.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userlikequestion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.RemovedLikesIDs(); len(nodes) > 0 && !quo.mutation.LikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.LikesTable,
			Columns: []string{question.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userlikequestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.LikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.LikesTable,
			Columns: []string{question.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userlikequestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if quo.mutation.FavoritesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.FavoritesTable,
			Columns: []string{question.FavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfavoritequestion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.RemovedFavoritesIDs(); len(nodes) > 0 && !quo.mutation.FavoritesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.FavoritesTable,
			Columns: []string{question.FavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfavoritequestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.FavoritesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.FavoritesTable,
			Columns: []string{question.FavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfavoritequestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Question{config: quo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, quo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	quo.mutation.done = true
	return _node, nil
}
