// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/post"
	"backend/internal/ent/user"
	"backend/internal/ent/userfavoritepost"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserFavoritePostCreate is the builder for creating a UserFavoritePost entity.
type UserFavoritePostCreate struct {
	config
	mutation *UserFavoritePostMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (ufpc *UserFavoritePostCreate) SetUserID(i int) *UserFavoritePostCreate {
	ufpc.mutation.SetUserID(i)
	return ufpc
}

// SetPostID sets the "post_id" field.
func (ufpc *UserFavoritePostCreate) SetPostID(i int) *UserFavoritePostCreate {
	ufpc.mutation.SetPostID(i)
	return ufpc
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (ufpc *UserFavoritePostCreate) AddUserIDs(ids ...int) *UserFavoritePostCreate {
	ufpc.mutation.AddUserIDs(ids...)
	return ufpc
}

// AddUser adds the "user" edges to the User entity.
func (ufpc *UserFavoritePostCreate) AddUser(u ...*User) *UserFavoritePostCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ufpc.AddUserIDs(ids...)
}

// AddPostIDs adds the "post" edge to the Post entity by IDs.
func (ufpc *UserFavoritePostCreate) AddPostIDs(ids ...int) *UserFavoritePostCreate {
	ufpc.mutation.AddPostIDs(ids...)
	return ufpc
}

// AddPost adds the "post" edges to the Post entity.
func (ufpc *UserFavoritePostCreate) AddPost(p ...*Post) *UserFavoritePostCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ufpc.AddPostIDs(ids...)
}

// Mutation returns the UserFavoritePostMutation object of the builder.
func (ufpc *UserFavoritePostCreate) Mutation() *UserFavoritePostMutation {
	return ufpc.mutation
}

// Save creates the UserFavoritePost in the database.
func (ufpc *UserFavoritePostCreate) Save(ctx context.Context) (*UserFavoritePost, error) {
	return withHooks(ctx, ufpc.sqlSave, ufpc.mutation, ufpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ufpc *UserFavoritePostCreate) SaveX(ctx context.Context) *UserFavoritePost {
	v, err := ufpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ufpc *UserFavoritePostCreate) Exec(ctx context.Context) error {
	_, err := ufpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufpc *UserFavoritePostCreate) ExecX(ctx context.Context) {
	if err := ufpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ufpc *UserFavoritePostCreate) check() error {
	if _, ok := ufpc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserFavoritePost.user_id"`)}
	}
	if _, ok := ufpc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "UserFavoritePost.post_id"`)}
	}
	return nil
}

func (ufpc *UserFavoritePostCreate) sqlSave(ctx context.Context) (*UserFavoritePost, error) {
	if err := ufpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ufpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ufpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ufpc.mutation.id = &_node.ID
	ufpc.mutation.done = true
	return _node, nil
}

func (ufpc *UserFavoritePostCreate) createSpec() (*UserFavoritePost, *sqlgraph.CreateSpec) {
	var (
		_node = &UserFavoritePost{config: ufpc.config}
		_spec = sqlgraph.NewCreateSpec(userfavoritepost.Table, sqlgraph.NewFieldSpec(userfavoritepost.FieldID, field.TypeInt))
	)
	if value, ok := ufpc.mutation.UserID(); ok {
		_spec.SetField(userfavoritepost.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := ufpc.mutation.PostID(); ok {
		_spec.SetField(userfavoritepost.FieldPostID, field.TypeInt, value)
		_node.PostID = value
	}
	if nodes := ufpc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.UserTable,
			Columns: []string{userfavoritepost.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ufpc.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.PostTable,
			Columns: []string{userfavoritepost.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserFavoritePostCreateBulk is the builder for creating many UserFavoritePost entities in bulk.
type UserFavoritePostCreateBulk struct {
	config
	err      error
	builders []*UserFavoritePostCreate
}

// Save creates the UserFavoritePost entities in the database.
func (ufpcb *UserFavoritePostCreateBulk) Save(ctx context.Context) ([]*UserFavoritePost, error) {
	if ufpcb.err != nil {
		return nil, ufpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ufpcb.builders))
	nodes := make([]*UserFavoritePost, len(ufpcb.builders))
	mutators := make([]Mutator, len(ufpcb.builders))
	for i := range ufpcb.builders {
		func(i int, root context.Context) {
			builder := ufpcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserFavoritePostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ufpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ufpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ufpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ufpcb *UserFavoritePostCreateBulk) SaveX(ctx context.Context) []*UserFavoritePost {
	v, err := ufpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ufpcb *UserFavoritePostCreateBulk) Exec(ctx context.Context) error {
	_, err := ufpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufpcb *UserFavoritePostCreateBulk) ExecX(ctx context.Context) {
	if err := ufpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
