// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/question"
	"backend/internal/ent/user"
	"backend/internal/ent/userlikequestion"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserLikeQuestionCreate is the builder for creating a UserLikeQuestion entity.
type UserLikeQuestionCreate struct {
	config
	mutation *UserLikeQuestionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (ulqc *UserLikeQuestionCreate) SetUserID(i int) *UserLikeQuestionCreate {
	ulqc.mutation.SetUserID(i)
	return ulqc
}

// SetQuestionID sets the "question_id" field.
func (ulqc *UserLikeQuestionCreate) SetQuestionID(i int) *UserLikeQuestionCreate {
	ulqc.mutation.SetQuestionID(i)
	return ulqc
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (ulqc *UserLikeQuestionCreate) AddUserIDs(ids ...int) *UserLikeQuestionCreate {
	ulqc.mutation.AddUserIDs(ids...)
	return ulqc
}

// AddUser adds the "user" edges to the User entity.
func (ulqc *UserLikeQuestionCreate) AddUser(u ...*User) *UserLikeQuestionCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ulqc.AddUserIDs(ids...)
}

// AddQuestionIDs adds the "question" edge to the Question entity by IDs.
func (ulqc *UserLikeQuestionCreate) AddQuestionIDs(ids ...int) *UserLikeQuestionCreate {
	ulqc.mutation.AddQuestionIDs(ids...)
	return ulqc
}

// AddQuestion adds the "question" edges to the Question entity.
func (ulqc *UserLikeQuestionCreate) AddQuestion(q ...*Question) *UserLikeQuestionCreate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return ulqc.AddQuestionIDs(ids...)
}

// Mutation returns the UserLikeQuestionMutation object of the builder.
func (ulqc *UserLikeQuestionCreate) Mutation() *UserLikeQuestionMutation {
	return ulqc.mutation
}

// Save creates the UserLikeQuestion in the database.
func (ulqc *UserLikeQuestionCreate) Save(ctx context.Context) (*UserLikeQuestion, error) {
	return withHooks(ctx, ulqc.sqlSave, ulqc.mutation, ulqc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ulqc *UserLikeQuestionCreate) SaveX(ctx context.Context) *UserLikeQuestion {
	v, err := ulqc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ulqc *UserLikeQuestionCreate) Exec(ctx context.Context) error {
	_, err := ulqc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulqc *UserLikeQuestionCreate) ExecX(ctx context.Context) {
	if err := ulqc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ulqc *UserLikeQuestionCreate) check() error {
	if _, ok := ulqc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserLikeQuestion.user_id"`)}
	}
	if _, ok := ulqc.mutation.QuestionID(); !ok {
		return &ValidationError{Name: "question_id", err: errors.New(`ent: missing required field "UserLikeQuestion.question_id"`)}
	}
	return nil
}

func (ulqc *UserLikeQuestionCreate) sqlSave(ctx context.Context) (*UserLikeQuestion, error) {
	if err := ulqc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ulqc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ulqc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ulqc.mutation.id = &_node.ID
	ulqc.mutation.done = true
	return _node, nil
}

func (ulqc *UserLikeQuestionCreate) createSpec() (*UserLikeQuestion, *sqlgraph.CreateSpec) {
	var (
		_node = &UserLikeQuestion{config: ulqc.config}
		_spec = sqlgraph.NewCreateSpec(userlikequestion.Table, sqlgraph.NewFieldSpec(userlikequestion.FieldID, field.TypeInt))
	)
	if value, ok := ulqc.mutation.UserID(); ok {
		_spec.SetField(userlikequestion.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := ulqc.mutation.QuestionID(); ok {
		_spec.SetField(userlikequestion.FieldQuestionID, field.TypeInt, value)
		_node.QuestionID = value
	}
	if nodes := ulqc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userlikequestion.UserTable,
			Columns: []string{userlikequestion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ulqc.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userlikequestion.QuestionTable,
			Columns: []string{userlikequestion.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserLikeQuestionCreateBulk is the builder for creating many UserLikeQuestion entities in bulk.
type UserLikeQuestionCreateBulk struct {
	config
	err      error
	builders []*UserLikeQuestionCreate
}

// Save creates the UserLikeQuestion entities in the database.
func (ulqcb *UserLikeQuestionCreateBulk) Save(ctx context.Context) ([]*UserLikeQuestion, error) {
	if ulqcb.err != nil {
		return nil, ulqcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ulqcb.builders))
	nodes := make([]*UserLikeQuestion, len(ulqcb.builders))
	mutators := make([]Mutator, len(ulqcb.builders))
	for i := range ulqcb.builders {
		func(i int, root context.Context) {
			builder := ulqcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserLikeQuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ulqcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ulqcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ulqcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ulqcb *UserLikeQuestionCreateBulk) SaveX(ctx context.Context) []*UserLikeQuestion {
	v, err := ulqcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ulqcb *UserLikeQuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := ulqcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulqcb *UserLikeQuestionCreateBulk) ExecX(ctx context.Context) {
	if err := ulqcb.Exec(ctx); err != nil {
		panic(err)
	}
}
