// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/predicate"
	"backend/internal/ent/userfavoritepost"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserFavoritePostDelete is the builder for deleting a UserFavoritePost entity.
type UserFavoritePostDelete struct {
	config
	hooks    []Hook
	mutation *UserFavoritePostMutation
}

// Where appends a list predicates to the UserFavoritePostDelete builder.
func (ufpd *UserFavoritePostDelete) Where(ps ...predicate.UserFavoritePost) *UserFavoritePostDelete {
	ufpd.mutation.Where(ps...)
	return ufpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ufpd *UserFavoritePostDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ufpd.sqlExec, ufpd.mutation, ufpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ufpd *UserFavoritePostDelete) ExecX(ctx context.Context) int {
	n, err := ufpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ufpd *UserFavoritePostDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userfavoritepost.Table, sqlgraph.NewFieldSpec(userfavoritepost.FieldID, field.TypeInt))
	if ps := ufpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ufpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ufpd.mutation.done = true
	return affected, err
}

// UserFavoritePostDeleteOne is the builder for deleting a single UserFavoritePost entity.
type UserFavoritePostDeleteOne struct {
	ufpd *UserFavoritePostDelete
}

// Where appends a list predicates to the UserFavoritePostDelete builder.
func (ufpdo *UserFavoritePostDeleteOne) Where(ps ...predicate.UserFavoritePost) *UserFavoritePostDeleteOne {
	ufpdo.ufpd.mutation.Where(ps...)
	return ufpdo
}

// Exec executes the deletion query.
func (ufpdo *UserFavoritePostDeleteOne) Exec(ctx context.Context) error {
	n, err := ufpdo.ufpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userfavoritepost.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ufpdo *UserFavoritePostDeleteOne) ExecX(ctx context.Context) {
	if err := ufpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
