// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/question"
	"backend/internal/ent/user"
	"backend/internal/ent/userfavoritequestion"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserFavoriteQuestionCreate is the builder for creating a UserFavoriteQuestion entity.
type UserFavoriteQuestionCreate struct {
	config
	mutation *UserFavoriteQuestionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (ufqc *UserFavoriteQuestionCreate) SetUserID(i int) *UserFavoriteQuestionCreate {
	ufqc.mutation.SetUserID(i)
	return ufqc
}

// SetQuestionID sets the "question_id" field.
func (ufqc *UserFavoriteQuestionCreate) SetQuestionID(i int) *UserFavoriteQuestionCreate {
	ufqc.mutation.SetQuestionID(i)
	return ufqc
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (ufqc *UserFavoriteQuestionCreate) AddUserIDs(ids ...int) *UserFavoriteQuestionCreate {
	ufqc.mutation.AddUserIDs(ids...)
	return ufqc
}

// AddUser adds the "user" edges to the User entity.
func (ufqc *UserFavoriteQuestionCreate) AddUser(u ...*User) *UserFavoriteQuestionCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ufqc.AddUserIDs(ids...)
}

// AddQuestionIDs adds the "question" edge to the Question entity by IDs.
func (ufqc *UserFavoriteQuestionCreate) AddQuestionIDs(ids ...int) *UserFavoriteQuestionCreate {
	ufqc.mutation.AddQuestionIDs(ids...)
	return ufqc
}

// AddQuestion adds the "question" edges to the Question entity.
func (ufqc *UserFavoriteQuestionCreate) AddQuestion(q ...*Question) *UserFavoriteQuestionCreate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return ufqc.AddQuestionIDs(ids...)
}

// Mutation returns the UserFavoriteQuestionMutation object of the builder.
func (ufqc *UserFavoriteQuestionCreate) Mutation() *UserFavoriteQuestionMutation {
	return ufqc.mutation
}

// Save creates the UserFavoriteQuestion in the database.
func (ufqc *UserFavoriteQuestionCreate) Save(ctx context.Context) (*UserFavoriteQuestion, error) {
	return withHooks(ctx, ufqc.sqlSave, ufqc.mutation, ufqc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ufqc *UserFavoriteQuestionCreate) SaveX(ctx context.Context) *UserFavoriteQuestion {
	v, err := ufqc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ufqc *UserFavoriteQuestionCreate) Exec(ctx context.Context) error {
	_, err := ufqc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufqc *UserFavoriteQuestionCreate) ExecX(ctx context.Context) {
	if err := ufqc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ufqc *UserFavoriteQuestionCreate) check() error {
	if _, ok := ufqc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserFavoriteQuestion.user_id"`)}
	}
	if _, ok := ufqc.mutation.QuestionID(); !ok {
		return &ValidationError{Name: "question_id", err: errors.New(`ent: missing required field "UserFavoriteQuestion.question_id"`)}
	}
	return nil
}

func (ufqc *UserFavoriteQuestionCreate) sqlSave(ctx context.Context) (*UserFavoriteQuestion, error) {
	if err := ufqc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ufqc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ufqc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ufqc.mutation.id = &_node.ID
	ufqc.mutation.done = true
	return _node, nil
}

func (ufqc *UserFavoriteQuestionCreate) createSpec() (*UserFavoriteQuestion, *sqlgraph.CreateSpec) {
	var (
		_node = &UserFavoriteQuestion{config: ufqc.config}
		_spec = sqlgraph.NewCreateSpec(userfavoritequestion.Table, sqlgraph.NewFieldSpec(userfavoritequestion.FieldID, field.TypeInt))
	)
	if value, ok := ufqc.mutation.UserID(); ok {
		_spec.SetField(userfavoritequestion.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := ufqc.mutation.QuestionID(); ok {
		_spec.SetField(userfavoritequestion.FieldQuestionID, field.TypeInt, value)
		_node.QuestionID = value
	}
	if nodes := ufqc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritequestion.UserTable,
			Columns: []string{userfavoritequestion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ufqc.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritequestion.QuestionTable,
			Columns: []string{userfavoritequestion.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserFavoriteQuestionCreateBulk is the builder for creating many UserFavoriteQuestion entities in bulk.
type UserFavoriteQuestionCreateBulk struct {
	config
	err      error
	builders []*UserFavoriteQuestionCreate
}

// Save creates the UserFavoriteQuestion entities in the database.
func (ufqcb *UserFavoriteQuestionCreateBulk) Save(ctx context.Context) ([]*UserFavoriteQuestion, error) {
	if ufqcb.err != nil {
		return nil, ufqcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ufqcb.builders))
	nodes := make([]*UserFavoriteQuestion, len(ufqcb.builders))
	mutators := make([]Mutator, len(ufqcb.builders))
	for i := range ufqcb.builders {
		func(i int, root context.Context) {
			builder := ufqcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserFavoriteQuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ufqcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ufqcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ufqcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ufqcb *UserFavoriteQuestionCreateBulk) SaveX(ctx context.Context) []*UserFavoriteQuestion {
	v, err := ufqcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ufqcb *UserFavoriteQuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := ufqcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufqcb *UserFavoriteQuestionCreateBulk) ExecX(ctx context.Context) {
	if err := ufqcb.Exec(ctx); err != nil {
		panic(err)
	}
}
