// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/post"
	"backend/internal/ent/predicate"
	"backend/internal/ent/user"
	"backend/internal/ent/userfavoritepost"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserFavoritePostUpdate is the builder for updating UserFavoritePost entities.
type UserFavoritePostUpdate struct {
	config
	hooks    []Hook
	mutation *UserFavoritePostMutation
}

// Where appends a list predicates to the UserFavoritePostUpdate builder.
func (ufpu *UserFavoritePostUpdate) Where(ps ...predicate.UserFavoritePost) *UserFavoritePostUpdate {
	ufpu.mutation.Where(ps...)
	return ufpu
}

// SetUserID sets the "user_id" field.
func (ufpu *UserFavoritePostUpdate) SetUserID(i int) *UserFavoritePostUpdate {
	ufpu.mutation.ResetUserID()
	ufpu.mutation.SetUserID(i)
	return ufpu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ufpu *UserFavoritePostUpdate) SetNillableUserID(i *int) *UserFavoritePostUpdate {
	if i != nil {
		ufpu.SetUserID(*i)
	}
	return ufpu
}

// AddUserID adds i to the "user_id" field.
func (ufpu *UserFavoritePostUpdate) AddUserID(i int) *UserFavoritePostUpdate {
	ufpu.mutation.AddUserID(i)
	return ufpu
}

// SetPostID sets the "post_id" field.
func (ufpu *UserFavoritePostUpdate) SetPostID(i int) *UserFavoritePostUpdate {
	ufpu.mutation.ResetPostID()
	ufpu.mutation.SetPostID(i)
	return ufpu
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (ufpu *UserFavoritePostUpdate) SetNillablePostID(i *int) *UserFavoritePostUpdate {
	if i != nil {
		ufpu.SetPostID(*i)
	}
	return ufpu
}

// AddPostID adds i to the "post_id" field.
func (ufpu *UserFavoritePostUpdate) AddPostID(i int) *UserFavoritePostUpdate {
	ufpu.mutation.AddPostID(i)
	return ufpu
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (ufpu *UserFavoritePostUpdate) AddUserIDs(ids ...int) *UserFavoritePostUpdate {
	ufpu.mutation.AddUserIDs(ids...)
	return ufpu
}

// AddUser adds the "user" edges to the User entity.
func (ufpu *UserFavoritePostUpdate) AddUser(u ...*User) *UserFavoritePostUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ufpu.AddUserIDs(ids...)
}

// AddPostIDs adds the "post" edge to the Post entity by IDs.
func (ufpu *UserFavoritePostUpdate) AddPostIDs(ids ...int) *UserFavoritePostUpdate {
	ufpu.mutation.AddPostIDs(ids...)
	return ufpu
}

// AddPost adds the "post" edges to the Post entity.
func (ufpu *UserFavoritePostUpdate) AddPost(p ...*Post) *UserFavoritePostUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ufpu.AddPostIDs(ids...)
}

// Mutation returns the UserFavoritePostMutation object of the builder.
func (ufpu *UserFavoritePostUpdate) Mutation() *UserFavoritePostMutation {
	return ufpu.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (ufpu *UserFavoritePostUpdate) ClearUser() *UserFavoritePostUpdate {
	ufpu.mutation.ClearUser()
	return ufpu
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (ufpu *UserFavoritePostUpdate) RemoveUserIDs(ids ...int) *UserFavoritePostUpdate {
	ufpu.mutation.RemoveUserIDs(ids...)
	return ufpu
}

// RemoveUser removes "user" edges to User entities.
func (ufpu *UserFavoritePostUpdate) RemoveUser(u ...*User) *UserFavoritePostUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ufpu.RemoveUserIDs(ids...)
}

// ClearPost clears all "post" edges to the Post entity.
func (ufpu *UserFavoritePostUpdate) ClearPost() *UserFavoritePostUpdate {
	ufpu.mutation.ClearPost()
	return ufpu
}

// RemovePostIDs removes the "post" edge to Post entities by IDs.
func (ufpu *UserFavoritePostUpdate) RemovePostIDs(ids ...int) *UserFavoritePostUpdate {
	ufpu.mutation.RemovePostIDs(ids...)
	return ufpu
}

// RemovePost removes "post" edges to Post entities.
func (ufpu *UserFavoritePostUpdate) RemovePost(p ...*Post) *UserFavoritePostUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ufpu.RemovePostIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ufpu *UserFavoritePostUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ufpu.sqlSave, ufpu.mutation, ufpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ufpu *UserFavoritePostUpdate) SaveX(ctx context.Context) int {
	affected, err := ufpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ufpu *UserFavoritePostUpdate) Exec(ctx context.Context) error {
	_, err := ufpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufpu *UserFavoritePostUpdate) ExecX(ctx context.Context) {
	if err := ufpu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ufpu *UserFavoritePostUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userfavoritepost.Table, userfavoritepost.Columns, sqlgraph.NewFieldSpec(userfavoritepost.FieldID, field.TypeInt))
	if ps := ufpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ufpu.mutation.UserID(); ok {
		_spec.SetField(userfavoritepost.FieldUserID, field.TypeInt, value)
	}
	if value, ok := ufpu.mutation.AddedUserID(); ok {
		_spec.AddField(userfavoritepost.FieldUserID, field.TypeInt, value)
	}
	if value, ok := ufpu.mutation.PostID(); ok {
		_spec.SetField(userfavoritepost.FieldPostID, field.TypeInt, value)
	}
	if value, ok := ufpu.mutation.AddedPostID(); ok {
		_spec.AddField(userfavoritepost.FieldPostID, field.TypeInt, value)
	}
	if ufpu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.UserTable,
			Columns: []string{userfavoritepost.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ufpu.mutation.RemovedUserIDs(); len(nodes) > 0 && !ufpu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.UserTable,
			Columns: []string{userfavoritepost.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ufpu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.UserTable,
			Columns: []string{userfavoritepost.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ufpu.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.PostTable,
			Columns: []string{userfavoritepost.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ufpu.mutation.RemovedPostIDs(); len(nodes) > 0 && !ufpu.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.PostTable,
			Columns: []string{userfavoritepost.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ufpu.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.PostTable,
			Columns: []string{userfavoritepost.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ufpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userfavoritepost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ufpu.mutation.done = true
	return n, nil
}

// UserFavoritePostUpdateOne is the builder for updating a single UserFavoritePost entity.
type UserFavoritePostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserFavoritePostMutation
}

// SetUserID sets the "user_id" field.
func (ufpuo *UserFavoritePostUpdateOne) SetUserID(i int) *UserFavoritePostUpdateOne {
	ufpuo.mutation.ResetUserID()
	ufpuo.mutation.SetUserID(i)
	return ufpuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ufpuo *UserFavoritePostUpdateOne) SetNillableUserID(i *int) *UserFavoritePostUpdateOne {
	if i != nil {
		ufpuo.SetUserID(*i)
	}
	return ufpuo
}

// AddUserID adds i to the "user_id" field.
func (ufpuo *UserFavoritePostUpdateOne) AddUserID(i int) *UserFavoritePostUpdateOne {
	ufpuo.mutation.AddUserID(i)
	return ufpuo
}

// SetPostID sets the "post_id" field.
func (ufpuo *UserFavoritePostUpdateOne) SetPostID(i int) *UserFavoritePostUpdateOne {
	ufpuo.mutation.ResetPostID()
	ufpuo.mutation.SetPostID(i)
	return ufpuo
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (ufpuo *UserFavoritePostUpdateOne) SetNillablePostID(i *int) *UserFavoritePostUpdateOne {
	if i != nil {
		ufpuo.SetPostID(*i)
	}
	return ufpuo
}

// AddPostID adds i to the "post_id" field.
func (ufpuo *UserFavoritePostUpdateOne) AddPostID(i int) *UserFavoritePostUpdateOne {
	ufpuo.mutation.AddPostID(i)
	return ufpuo
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (ufpuo *UserFavoritePostUpdateOne) AddUserIDs(ids ...int) *UserFavoritePostUpdateOne {
	ufpuo.mutation.AddUserIDs(ids...)
	return ufpuo
}

// AddUser adds the "user" edges to the User entity.
func (ufpuo *UserFavoritePostUpdateOne) AddUser(u ...*User) *UserFavoritePostUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ufpuo.AddUserIDs(ids...)
}

// AddPostIDs adds the "post" edge to the Post entity by IDs.
func (ufpuo *UserFavoritePostUpdateOne) AddPostIDs(ids ...int) *UserFavoritePostUpdateOne {
	ufpuo.mutation.AddPostIDs(ids...)
	return ufpuo
}

// AddPost adds the "post" edges to the Post entity.
func (ufpuo *UserFavoritePostUpdateOne) AddPost(p ...*Post) *UserFavoritePostUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ufpuo.AddPostIDs(ids...)
}

// Mutation returns the UserFavoritePostMutation object of the builder.
func (ufpuo *UserFavoritePostUpdateOne) Mutation() *UserFavoritePostMutation {
	return ufpuo.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (ufpuo *UserFavoritePostUpdateOne) ClearUser() *UserFavoritePostUpdateOne {
	ufpuo.mutation.ClearUser()
	return ufpuo
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (ufpuo *UserFavoritePostUpdateOne) RemoveUserIDs(ids ...int) *UserFavoritePostUpdateOne {
	ufpuo.mutation.RemoveUserIDs(ids...)
	return ufpuo
}

// RemoveUser removes "user" edges to User entities.
func (ufpuo *UserFavoritePostUpdateOne) RemoveUser(u ...*User) *UserFavoritePostUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ufpuo.RemoveUserIDs(ids...)
}

// ClearPost clears all "post" edges to the Post entity.
func (ufpuo *UserFavoritePostUpdateOne) ClearPost() *UserFavoritePostUpdateOne {
	ufpuo.mutation.ClearPost()
	return ufpuo
}

// RemovePostIDs removes the "post" edge to Post entities by IDs.
func (ufpuo *UserFavoritePostUpdateOne) RemovePostIDs(ids ...int) *UserFavoritePostUpdateOne {
	ufpuo.mutation.RemovePostIDs(ids...)
	return ufpuo
}

// RemovePost removes "post" edges to Post entities.
func (ufpuo *UserFavoritePostUpdateOne) RemovePost(p ...*Post) *UserFavoritePostUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ufpuo.RemovePostIDs(ids...)
}

// Where appends a list predicates to the UserFavoritePostUpdate builder.
func (ufpuo *UserFavoritePostUpdateOne) Where(ps ...predicate.UserFavoritePost) *UserFavoritePostUpdateOne {
	ufpuo.mutation.Where(ps...)
	return ufpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ufpuo *UserFavoritePostUpdateOne) Select(field string, fields ...string) *UserFavoritePostUpdateOne {
	ufpuo.fields = append([]string{field}, fields...)
	return ufpuo
}

// Save executes the query and returns the updated UserFavoritePost entity.
func (ufpuo *UserFavoritePostUpdateOne) Save(ctx context.Context) (*UserFavoritePost, error) {
	return withHooks(ctx, ufpuo.sqlSave, ufpuo.mutation, ufpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ufpuo *UserFavoritePostUpdateOne) SaveX(ctx context.Context) *UserFavoritePost {
	node, err := ufpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ufpuo *UserFavoritePostUpdateOne) Exec(ctx context.Context) error {
	_, err := ufpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufpuo *UserFavoritePostUpdateOne) ExecX(ctx context.Context) {
	if err := ufpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ufpuo *UserFavoritePostUpdateOne) sqlSave(ctx context.Context) (_node *UserFavoritePost, err error) {
	_spec := sqlgraph.NewUpdateSpec(userfavoritepost.Table, userfavoritepost.Columns, sqlgraph.NewFieldSpec(userfavoritepost.FieldID, field.TypeInt))
	id, ok := ufpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserFavoritePost.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ufpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userfavoritepost.FieldID)
		for _, f := range fields {
			if !userfavoritepost.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userfavoritepost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ufpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ufpuo.mutation.UserID(); ok {
		_spec.SetField(userfavoritepost.FieldUserID, field.TypeInt, value)
	}
	if value, ok := ufpuo.mutation.AddedUserID(); ok {
		_spec.AddField(userfavoritepost.FieldUserID, field.TypeInt, value)
	}
	if value, ok := ufpuo.mutation.PostID(); ok {
		_spec.SetField(userfavoritepost.FieldPostID, field.TypeInt, value)
	}
	if value, ok := ufpuo.mutation.AddedPostID(); ok {
		_spec.AddField(userfavoritepost.FieldPostID, field.TypeInt, value)
	}
	if ufpuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.UserTable,
			Columns: []string{userfavoritepost.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ufpuo.mutation.RemovedUserIDs(); len(nodes) > 0 && !ufpuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.UserTable,
			Columns: []string{userfavoritepost.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ufpuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.UserTable,
			Columns: []string{userfavoritepost.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ufpuo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.PostTable,
			Columns: []string{userfavoritepost.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ufpuo.mutation.RemovedPostIDs(); len(nodes) > 0 && !ufpuo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.PostTable,
			Columns: []string{userfavoritepost.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ufpuo.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userfavoritepost.PostTable,
			Columns: []string{userfavoritepost.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserFavoritePost{config: ufpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ufpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userfavoritepost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ufpuo.mutation.done = true
	return _node, nil
}
