// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/predicate"
	"backend/internal/ent/question"
	"backend/internal/ent/user"
	"backend/internal/ent/userlikequestion"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserLikeQuestionQuery is the builder for querying UserLikeQuestion entities.
type UserLikeQuestionQuery struct {
	config
	ctx          *QueryContext
	order        []userlikequestion.OrderOption
	inters       []Interceptor
	predicates   []predicate.UserLikeQuestion
	withUser     *UserQuery
	withQuestion *QuestionQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserLikeQuestionQuery builder.
func (ulqq *UserLikeQuestionQuery) Where(ps ...predicate.UserLikeQuestion) *UserLikeQuestionQuery {
	ulqq.predicates = append(ulqq.predicates, ps...)
	return ulqq
}

// Limit the number of records to be returned by this query.
func (ulqq *UserLikeQuestionQuery) Limit(limit int) *UserLikeQuestionQuery {
	ulqq.ctx.Limit = &limit
	return ulqq
}

// Offset to start from.
func (ulqq *UserLikeQuestionQuery) Offset(offset int) *UserLikeQuestionQuery {
	ulqq.ctx.Offset = &offset
	return ulqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ulqq *UserLikeQuestionQuery) Unique(unique bool) *UserLikeQuestionQuery {
	ulqq.ctx.Unique = &unique
	return ulqq
}

// Order specifies how the records should be ordered.
func (ulqq *UserLikeQuestionQuery) Order(o ...userlikequestion.OrderOption) *UserLikeQuestionQuery {
	ulqq.order = append(ulqq.order, o...)
	return ulqq
}

// QueryUser chains the current query on the "user" edge.
func (ulqq *UserLikeQuestionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ulqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ulqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ulqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userlikequestion.Table, userlikequestion.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userlikequestion.UserTable, userlikequestion.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ulqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryQuestion chains the current query on the "question" edge.
func (ulqq *UserLikeQuestionQuery) QueryQuestion() *QuestionQuery {
	query := (&QuestionClient{config: ulqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ulqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ulqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userlikequestion.Table, userlikequestion.FieldID, selector),
			sqlgraph.To(question.Table, question.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userlikequestion.QuestionTable, userlikequestion.QuestionColumn),
		)
		fromU = sqlgraph.SetNeighbors(ulqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserLikeQuestion entity from the query.
// Returns a *NotFoundError when no UserLikeQuestion was found.
func (ulqq *UserLikeQuestionQuery) First(ctx context.Context) (*UserLikeQuestion, error) {
	nodes, err := ulqq.Limit(1).All(setContextOp(ctx, ulqq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userlikequestion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ulqq *UserLikeQuestionQuery) FirstX(ctx context.Context) *UserLikeQuestion {
	node, err := ulqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserLikeQuestion ID from the query.
// Returns a *NotFoundError when no UserLikeQuestion ID was found.
func (ulqq *UserLikeQuestionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulqq.Limit(1).IDs(setContextOp(ctx, ulqq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userlikequestion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ulqq *UserLikeQuestionQuery) FirstIDX(ctx context.Context) int {
	id, err := ulqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserLikeQuestion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserLikeQuestion entity is found.
// Returns a *NotFoundError when no UserLikeQuestion entities are found.
func (ulqq *UserLikeQuestionQuery) Only(ctx context.Context) (*UserLikeQuestion, error) {
	nodes, err := ulqq.Limit(2).All(setContextOp(ctx, ulqq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userlikequestion.Label}
	default:
		return nil, &NotSingularError{userlikequestion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ulqq *UserLikeQuestionQuery) OnlyX(ctx context.Context) *UserLikeQuestion {
	node, err := ulqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserLikeQuestion ID in the query.
// Returns a *NotSingularError when more than one UserLikeQuestion ID is found.
// Returns a *NotFoundError when no entities are found.
func (ulqq *UserLikeQuestionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulqq.Limit(2).IDs(setContextOp(ctx, ulqq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userlikequestion.Label}
	default:
		err = &NotSingularError{userlikequestion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ulqq *UserLikeQuestionQuery) OnlyIDX(ctx context.Context) int {
	id, err := ulqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserLikeQuestions.
func (ulqq *UserLikeQuestionQuery) All(ctx context.Context) ([]*UserLikeQuestion, error) {
	ctx = setContextOp(ctx, ulqq.ctx, "All")
	if err := ulqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserLikeQuestion, *UserLikeQuestionQuery]()
	return withInterceptors[[]*UserLikeQuestion](ctx, ulqq, qr, ulqq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ulqq *UserLikeQuestionQuery) AllX(ctx context.Context) []*UserLikeQuestion {
	nodes, err := ulqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserLikeQuestion IDs.
func (ulqq *UserLikeQuestionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ulqq.ctx.Unique == nil && ulqq.path != nil {
		ulqq.Unique(true)
	}
	ctx = setContextOp(ctx, ulqq.ctx, "IDs")
	if err = ulqq.Select(userlikequestion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ulqq *UserLikeQuestionQuery) IDsX(ctx context.Context) []int {
	ids, err := ulqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ulqq *UserLikeQuestionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ulqq.ctx, "Count")
	if err := ulqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ulqq, querierCount[*UserLikeQuestionQuery](), ulqq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ulqq *UserLikeQuestionQuery) CountX(ctx context.Context) int {
	count, err := ulqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ulqq *UserLikeQuestionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ulqq.ctx, "Exist")
	switch _, err := ulqq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ulqq *UserLikeQuestionQuery) ExistX(ctx context.Context) bool {
	exist, err := ulqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserLikeQuestionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ulqq *UserLikeQuestionQuery) Clone() *UserLikeQuestionQuery {
	if ulqq == nil {
		return nil
	}
	return &UserLikeQuestionQuery{
		config:       ulqq.config,
		ctx:          ulqq.ctx.Clone(),
		order:        append([]userlikequestion.OrderOption{}, ulqq.order...),
		inters:       append([]Interceptor{}, ulqq.inters...),
		predicates:   append([]predicate.UserLikeQuestion{}, ulqq.predicates...),
		withUser:     ulqq.withUser.Clone(),
		withQuestion: ulqq.withQuestion.Clone(),
		// clone intermediate query.
		sql:  ulqq.sql.Clone(),
		path: ulqq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ulqq *UserLikeQuestionQuery) WithUser(opts ...func(*UserQuery)) *UserLikeQuestionQuery {
	query := (&UserClient{config: ulqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ulqq.withUser = query
	return ulqq
}

// WithQuestion tells the query-builder to eager-load the nodes that are connected to
// the "question" edge. The optional arguments are used to configure the query builder of the edge.
func (ulqq *UserLikeQuestionQuery) WithQuestion(opts ...func(*QuestionQuery)) *UserLikeQuestionQuery {
	query := (&QuestionClient{config: ulqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ulqq.withQuestion = query
	return ulqq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserLikeQuestion.Query().
//		GroupBy(userlikequestion.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ulqq *UserLikeQuestionQuery) GroupBy(field string, fields ...string) *UserLikeQuestionGroupBy {
	ulqq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserLikeQuestionGroupBy{build: ulqq}
	grbuild.flds = &ulqq.ctx.Fields
	grbuild.label = userlikequestion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UserLikeQuestion.Query().
//		Select(userlikequestion.FieldUserID).
//		Scan(ctx, &v)
func (ulqq *UserLikeQuestionQuery) Select(fields ...string) *UserLikeQuestionSelect {
	ulqq.ctx.Fields = append(ulqq.ctx.Fields, fields...)
	sbuild := &UserLikeQuestionSelect{UserLikeQuestionQuery: ulqq}
	sbuild.label = userlikequestion.Label
	sbuild.flds, sbuild.scan = &ulqq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserLikeQuestionSelect configured with the given aggregations.
func (ulqq *UserLikeQuestionQuery) Aggregate(fns ...AggregateFunc) *UserLikeQuestionSelect {
	return ulqq.Select().Aggregate(fns...)
}

func (ulqq *UserLikeQuestionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ulqq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ulqq); err != nil {
				return err
			}
		}
	}
	for _, f := range ulqq.ctx.Fields {
		if !userlikequestion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ulqq.path != nil {
		prev, err := ulqq.path(ctx)
		if err != nil {
			return err
		}
		ulqq.sql = prev
	}
	return nil
}

func (ulqq *UserLikeQuestionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserLikeQuestion, error) {
	var (
		nodes       = []*UserLikeQuestion{}
		withFKs     = ulqq.withFKs
		_spec       = ulqq.querySpec()
		loadedTypes = [2]bool{
			ulqq.withUser != nil,
			ulqq.withQuestion != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, userlikequestion.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserLikeQuestion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserLikeQuestion{config: ulqq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ulqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ulqq.withUser; query != nil {
		if err := ulqq.loadUser(ctx, query, nodes,
			func(n *UserLikeQuestion) { n.Edges.User = []*User{} },
			func(n *UserLikeQuestion, e *User) { n.Edges.User = append(n.Edges.User, e) }); err != nil {
			return nil, err
		}
	}
	if query := ulqq.withQuestion; query != nil {
		if err := ulqq.loadQuestion(ctx, query, nodes,
			func(n *UserLikeQuestion) { n.Edges.Question = []*Question{} },
			func(n *UserLikeQuestion, e *Question) { n.Edges.Question = append(n.Edges.Question, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ulqq *UserLikeQuestionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserLikeQuestion, init func(*UserLikeQuestion), assign func(*UserLikeQuestion, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*UserLikeQuestion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(userlikequestion.UserColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.user_like_question_user
		if fk == nil {
			return fmt.Errorf(`foreign-key "user_like_question_user" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_like_question_user" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (ulqq *UserLikeQuestionQuery) loadQuestion(ctx context.Context, query *QuestionQuery, nodes []*UserLikeQuestion, init func(*UserLikeQuestion), assign func(*UserLikeQuestion, *Question)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*UserLikeQuestion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Question(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(userlikequestion.QuestionColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.user_like_question_question
		if fk == nil {
			return fmt.Errorf(`foreign-key "user_like_question_question" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_like_question_question" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ulqq *UserLikeQuestionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ulqq.querySpec()
	_spec.Node.Columns = ulqq.ctx.Fields
	if len(ulqq.ctx.Fields) > 0 {
		_spec.Unique = ulqq.ctx.Unique != nil && *ulqq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ulqq.driver, _spec)
}

func (ulqq *UserLikeQuestionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userlikequestion.Table, userlikequestion.Columns, sqlgraph.NewFieldSpec(userlikequestion.FieldID, field.TypeInt))
	_spec.From = ulqq.sql
	if unique := ulqq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ulqq.path != nil {
		_spec.Unique = true
	}
	if fields := ulqq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userlikequestion.FieldID)
		for i := range fields {
			if fields[i] != userlikequestion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ulqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ulqq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ulqq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ulqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ulqq *UserLikeQuestionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ulqq.driver.Dialect())
	t1 := builder.Table(userlikequestion.Table)
	columns := ulqq.ctx.Fields
	if len(columns) == 0 {
		columns = userlikequestion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ulqq.sql != nil {
		selector = ulqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ulqq.ctx.Unique != nil && *ulqq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ulqq.predicates {
		p(selector)
	}
	for _, p := range ulqq.order {
		p(selector)
	}
	if offset := ulqq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ulqq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserLikeQuestionGroupBy is the group-by builder for UserLikeQuestion entities.
type UserLikeQuestionGroupBy struct {
	selector
	build *UserLikeQuestionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ulqgb *UserLikeQuestionGroupBy) Aggregate(fns ...AggregateFunc) *UserLikeQuestionGroupBy {
	ulqgb.fns = append(ulqgb.fns, fns...)
	return ulqgb
}

// Scan applies the selector query and scans the result into the given value.
func (ulqgb *UserLikeQuestionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulqgb.build.ctx, "GroupBy")
	if err := ulqgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserLikeQuestionQuery, *UserLikeQuestionGroupBy](ctx, ulqgb.build, ulqgb, ulqgb.build.inters, v)
}

func (ulqgb *UserLikeQuestionGroupBy) sqlScan(ctx context.Context, root *UserLikeQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ulqgb.fns))
	for _, fn := range ulqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ulqgb.flds)+len(ulqgb.fns))
		for _, f := range *ulqgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ulqgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulqgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserLikeQuestionSelect is the builder for selecting fields of UserLikeQuestion entities.
type UserLikeQuestionSelect struct {
	*UserLikeQuestionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ulqs *UserLikeQuestionSelect) Aggregate(fns ...AggregateFunc) *UserLikeQuestionSelect {
	ulqs.fns = append(ulqs.fns, fns...)
	return ulqs
}

// Scan applies the selector query and scans the result into the given value.
func (ulqs *UserLikeQuestionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulqs.ctx, "Select")
	if err := ulqs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserLikeQuestionQuery, *UserLikeQuestionSelect](ctx, ulqs.UserLikeQuestionQuery, ulqs, ulqs.inters, v)
}

func (ulqs *UserLikeQuestionSelect) sqlScan(ctx context.Context, root *UserLikeQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ulqs.fns))
	for _, fn := range ulqs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ulqs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
