// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/predicate"
	"backend/internal/ent/userlikequestion"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserLikeQuestionDelete is the builder for deleting a UserLikeQuestion entity.
type UserLikeQuestionDelete struct {
	config
	hooks    []Hook
	mutation *UserLikeQuestionMutation
}

// Where appends a list predicates to the UserLikeQuestionDelete builder.
func (ulqd *UserLikeQuestionDelete) Where(ps ...predicate.UserLikeQuestion) *UserLikeQuestionDelete {
	ulqd.mutation.Where(ps...)
	return ulqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ulqd *UserLikeQuestionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ulqd.sqlExec, ulqd.mutation, ulqd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ulqd *UserLikeQuestionDelete) ExecX(ctx context.Context) int {
	n, err := ulqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ulqd *UserLikeQuestionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userlikequestion.Table, sqlgraph.NewFieldSpec(userlikequestion.FieldID, field.TypeInt))
	if ps := ulqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ulqd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ulqd.mutation.done = true
	return affected, err
}

// UserLikeQuestionDeleteOne is the builder for deleting a single UserLikeQuestion entity.
type UserLikeQuestionDeleteOne struct {
	ulqd *UserLikeQuestionDelete
}

// Where appends a list predicates to the UserLikeQuestionDelete builder.
func (ulqdo *UserLikeQuestionDeleteOne) Where(ps ...predicate.UserLikeQuestion) *UserLikeQuestionDeleteOne {
	ulqdo.ulqd.mutation.Where(ps...)
	return ulqdo
}

// Exec executes the deletion query.
func (ulqdo *UserLikeQuestionDeleteOne) Exec(ctx context.Context) error {
	n, err := ulqdo.ulqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userlikequestion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ulqdo *UserLikeQuestionDeleteOne) ExecX(ctx context.Context) {
	if err := ulqdo.Exec(ctx); err != nil {
		panic(err)
	}
}
