// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/post"
	"backend/internal/ent/predicate"
	"backend/internal/ent/user"
	"backend/internal/ent/userfavoritepost"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserFavoritePostQuery is the builder for querying UserFavoritePost entities.
type UserFavoritePostQuery struct {
	config
	ctx        *QueryContext
	order      []userfavoritepost.OrderOption
	inters     []Interceptor
	predicates []predicate.UserFavoritePost
	withUser   *UserQuery
	withPost   *PostQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserFavoritePostQuery builder.
func (ufpq *UserFavoritePostQuery) Where(ps ...predicate.UserFavoritePost) *UserFavoritePostQuery {
	ufpq.predicates = append(ufpq.predicates, ps...)
	return ufpq
}

// Limit the number of records to be returned by this query.
func (ufpq *UserFavoritePostQuery) Limit(limit int) *UserFavoritePostQuery {
	ufpq.ctx.Limit = &limit
	return ufpq
}

// Offset to start from.
func (ufpq *UserFavoritePostQuery) Offset(offset int) *UserFavoritePostQuery {
	ufpq.ctx.Offset = &offset
	return ufpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ufpq *UserFavoritePostQuery) Unique(unique bool) *UserFavoritePostQuery {
	ufpq.ctx.Unique = &unique
	return ufpq
}

// Order specifies how the records should be ordered.
func (ufpq *UserFavoritePostQuery) Order(o ...userfavoritepost.OrderOption) *UserFavoritePostQuery {
	ufpq.order = append(ufpq.order, o...)
	return ufpq
}

// QueryUser chains the current query on the "user" edge.
func (ufpq *UserFavoritePostQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ufpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ufpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ufpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userfavoritepost.Table, userfavoritepost.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userfavoritepost.UserTable, userfavoritepost.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ufpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPost chains the current query on the "post" edge.
func (ufpq *UserFavoritePostQuery) QueryPost() *PostQuery {
	query := (&PostClient{config: ufpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ufpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ufpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userfavoritepost.Table, userfavoritepost.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userfavoritepost.PostTable, userfavoritepost.PostColumn),
		)
		fromU = sqlgraph.SetNeighbors(ufpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserFavoritePost entity from the query.
// Returns a *NotFoundError when no UserFavoritePost was found.
func (ufpq *UserFavoritePostQuery) First(ctx context.Context) (*UserFavoritePost, error) {
	nodes, err := ufpq.Limit(1).All(setContextOp(ctx, ufpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userfavoritepost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ufpq *UserFavoritePostQuery) FirstX(ctx context.Context) *UserFavoritePost {
	node, err := ufpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserFavoritePost ID from the query.
// Returns a *NotFoundError when no UserFavoritePost ID was found.
func (ufpq *UserFavoritePostQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ufpq.Limit(1).IDs(setContextOp(ctx, ufpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userfavoritepost.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ufpq *UserFavoritePostQuery) FirstIDX(ctx context.Context) int {
	id, err := ufpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserFavoritePost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserFavoritePost entity is found.
// Returns a *NotFoundError when no UserFavoritePost entities are found.
func (ufpq *UserFavoritePostQuery) Only(ctx context.Context) (*UserFavoritePost, error) {
	nodes, err := ufpq.Limit(2).All(setContextOp(ctx, ufpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userfavoritepost.Label}
	default:
		return nil, &NotSingularError{userfavoritepost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ufpq *UserFavoritePostQuery) OnlyX(ctx context.Context) *UserFavoritePost {
	node, err := ufpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserFavoritePost ID in the query.
// Returns a *NotSingularError when more than one UserFavoritePost ID is found.
// Returns a *NotFoundError when no entities are found.
func (ufpq *UserFavoritePostQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ufpq.Limit(2).IDs(setContextOp(ctx, ufpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userfavoritepost.Label}
	default:
		err = &NotSingularError{userfavoritepost.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ufpq *UserFavoritePostQuery) OnlyIDX(ctx context.Context) int {
	id, err := ufpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserFavoritePosts.
func (ufpq *UserFavoritePostQuery) All(ctx context.Context) ([]*UserFavoritePost, error) {
	ctx = setContextOp(ctx, ufpq.ctx, "All")
	if err := ufpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserFavoritePost, *UserFavoritePostQuery]()
	return withInterceptors[[]*UserFavoritePost](ctx, ufpq, qr, ufpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ufpq *UserFavoritePostQuery) AllX(ctx context.Context) []*UserFavoritePost {
	nodes, err := ufpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserFavoritePost IDs.
func (ufpq *UserFavoritePostQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ufpq.ctx.Unique == nil && ufpq.path != nil {
		ufpq.Unique(true)
	}
	ctx = setContextOp(ctx, ufpq.ctx, "IDs")
	if err = ufpq.Select(userfavoritepost.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ufpq *UserFavoritePostQuery) IDsX(ctx context.Context) []int {
	ids, err := ufpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ufpq *UserFavoritePostQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ufpq.ctx, "Count")
	if err := ufpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ufpq, querierCount[*UserFavoritePostQuery](), ufpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ufpq *UserFavoritePostQuery) CountX(ctx context.Context) int {
	count, err := ufpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ufpq *UserFavoritePostQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ufpq.ctx, "Exist")
	switch _, err := ufpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ufpq *UserFavoritePostQuery) ExistX(ctx context.Context) bool {
	exist, err := ufpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserFavoritePostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ufpq *UserFavoritePostQuery) Clone() *UserFavoritePostQuery {
	if ufpq == nil {
		return nil
	}
	return &UserFavoritePostQuery{
		config:     ufpq.config,
		ctx:        ufpq.ctx.Clone(),
		order:      append([]userfavoritepost.OrderOption{}, ufpq.order...),
		inters:     append([]Interceptor{}, ufpq.inters...),
		predicates: append([]predicate.UserFavoritePost{}, ufpq.predicates...),
		withUser:   ufpq.withUser.Clone(),
		withPost:   ufpq.withPost.Clone(),
		// clone intermediate query.
		sql:  ufpq.sql.Clone(),
		path: ufpq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ufpq *UserFavoritePostQuery) WithUser(opts ...func(*UserQuery)) *UserFavoritePostQuery {
	query := (&UserClient{config: ufpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ufpq.withUser = query
	return ufpq
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (ufpq *UserFavoritePostQuery) WithPost(opts ...func(*PostQuery)) *UserFavoritePostQuery {
	query := (&PostClient{config: ufpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ufpq.withPost = query
	return ufpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserFavoritePost.Query().
//		GroupBy(userfavoritepost.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ufpq *UserFavoritePostQuery) GroupBy(field string, fields ...string) *UserFavoritePostGroupBy {
	ufpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserFavoritePostGroupBy{build: ufpq}
	grbuild.flds = &ufpq.ctx.Fields
	grbuild.label = userfavoritepost.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UserFavoritePost.Query().
//		Select(userfavoritepost.FieldUserID).
//		Scan(ctx, &v)
func (ufpq *UserFavoritePostQuery) Select(fields ...string) *UserFavoritePostSelect {
	ufpq.ctx.Fields = append(ufpq.ctx.Fields, fields...)
	sbuild := &UserFavoritePostSelect{UserFavoritePostQuery: ufpq}
	sbuild.label = userfavoritepost.Label
	sbuild.flds, sbuild.scan = &ufpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserFavoritePostSelect configured with the given aggregations.
func (ufpq *UserFavoritePostQuery) Aggregate(fns ...AggregateFunc) *UserFavoritePostSelect {
	return ufpq.Select().Aggregate(fns...)
}

func (ufpq *UserFavoritePostQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ufpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ufpq); err != nil {
				return err
			}
		}
	}
	for _, f := range ufpq.ctx.Fields {
		if !userfavoritepost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ufpq.path != nil {
		prev, err := ufpq.path(ctx)
		if err != nil {
			return err
		}
		ufpq.sql = prev
	}
	return nil
}

func (ufpq *UserFavoritePostQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserFavoritePost, error) {
	var (
		nodes       = []*UserFavoritePost{}
		withFKs     = ufpq.withFKs
		_spec       = ufpq.querySpec()
		loadedTypes = [2]bool{
			ufpq.withUser != nil,
			ufpq.withPost != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, userfavoritepost.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserFavoritePost).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserFavoritePost{config: ufpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ufpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ufpq.withUser; query != nil {
		if err := ufpq.loadUser(ctx, query, nodes,
			func(n *UserFavoritePost) { n.Edges.User = []*User{} },
			func(n *UserFavoritePost, e *User) { n.Edges.User = append(n.Edges.User, e) }); err != nil {
			return nil, err
		}
	}
	if query := ufpq.withPost; query != nil {
		if err := ufpq.loadPost(ctx, query, nodes,
			func(n *UserFavoritePost) { n.Edges.Post = []*Post{} },
			func(n *UserFavoritePost, e *Post) { n.Edges.Post = append(n.Edges.Post, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ufpq *UserFavoritePostQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserFavoritePost, init func(*UserFavoritePost), assign func(*UserFavoritePost, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*UserFavoritePost)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(userfavoritepost.UserColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.user_favorite_post_user
		if fk == nil {
			return fmt.Errorf(`foreign-key "user_favorite_post_user" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_favorite_post_user" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (ufpq *UserFavoritePostQuery) loadPost(ctx context.Context, query *PostQuery, nodes []*UserFavoritePost, init func(*UserFavoritePost), assign func(*UserFavoritePost, *Post)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*UserFavoritePost)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Post(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(userfavoritepost.PostColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.user_favorite_post_post
		if fk == nil {
			return fmt.Errorf(`foreign-key "user_favorite_post_post" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_favorite_post_post" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ufpq *UserFavoritePostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ufpq.querySpec()
	_spec.Node.Columns = ufpq.ctx.Fields
	if len(ufpq.ctx.Fields) > 0 {
		_spec.Unique = ufpq.ctx.Unique != nil && *ufpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ufpq.driver, _spec)
}

func (ufpq *UserFavoritePostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userfavoritepost.Table, userfavoritepost.Columns, sqlgraph.NewFieldSpec(userfavoritepost.FieldID, field.TypeInt))
	_spec.From = ufpq.sql
	if unique := ufpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ufpq.path != nil {
		_spec.Unique = true
	}
	if fields := ufpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userfavoritepost.FieldID)
		for i := range fields {
			if fields[i] != userfavoritepost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ufpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ufpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ufpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ufpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ufpq *UserFavoritePostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ufpq.driver.Dialect())
	t1 := builder.Table(userfavoritepost.Table)
	columns := ufpq.ctx.Fields
	if len(columns) == 0 {
		columns = userfavoritepost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ufpq.sql != nil {
		selector = ufpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ufpq.ctx.Unique != nil && *ufpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ufpq.predicates {
		p(selector)
	}
	for _, p := range ufpq.order {
		p(selector)
	}
	if offset := ufpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ufpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserFavoritePostGroupBy is the group-by builder for UserFavoritePost entities.
type UserFavoritePostGroupBy struct {
	selector
	build *UserFavoritePostQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ufpgb *UserFavoritePostGroupBy) Aggregate(fns ...AggregateFunc) *UserFavoritePostGroupBy {
	ufpgb.fns = append(ufpgb.fns, fns...)
	return ufpgb
}

// Scan applies the selector query and scans the result into the given value.
func (ufpgb *UserFavoritePostGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ufpgb.build.ctx, "GroupBy")
	if err := ufpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserFavoritePostQuery, *UserFavoritePostGroupBy](ctx, ufpgb.build, ufpgb, ufpgb.build.inters, v)
}

func (ufpgb *UserFavoritePostGroupBy) sqlScan(ctx context.Context, root *UserFavoritePostQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ufpgb.fns))
	for _, fn := range ufpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ufpgb.flds)+len(ufpgb.fns))
		for _, f := range *ufpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ufpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ufpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserFavoritePostSelect is the builder for selecting fields of UserFavoritePost entities.
type UserFavoritePostSelect struct {
	*UserFavoritePostQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ufps *UserFavoritePostSelect) Aggregate(fns ...AggregateFunc) *UserFavoritePostSelect {
	ufps.fns = append(ufps.fns, fns...)
	return ufps
}

// Scan applies the selector query and scans the result into the given value.
func (ufps *UserFavoritePostSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ufps.ctx, "Select")
	if err := ufps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserFavoritePostQuery, *UserFavoritePostSelect](ctx, ufps.UserFavoritePostQuery, ufps, ufps.inters, v)
}

func (ufps *UserFavoritePostSelect) sqlScan(ctx context.Context, root *UserFavoritePostQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ufps.fns))
	for _, fn := range ufps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ufps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ufps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
