// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// Nickname holds the value of the "nickname" field.
	Nickname string `json:"nickname,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// Avatar holds the value of the "avatar" field.
	Avatar string `json:"avatar,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges                       UserEdges `json:"edges"`
	comment_user                *int
	follow_follower             *int
	follow_following            *int
	post_user                   *int
	question_user               *int
	user_favorite_post_user     *int
	user_favorite_question_user *int
	user_like_post_user         *int
	user_like_question_user     *int
	selectValues                sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Posts holds the value of the posts edge.
	Posts []*Post `json:"posts,omitempty"`
	// Questions holds the value of the questions edge.
	Questions []*Question `json:"questions,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// LikePosts holds the value of the like_posts edge.
	LikePosts []*UserLikePost `json:"like_posts,omitempty"`
	// LikeQuestions holds the value of the like_questions edge.
	LikeQuestions []*UserLikeQuestion `json:"like_questions,omitempty"`
	// FavoritePosts holds the value of the favorite_posts edge.
	FavoritePosts []*UserFavoritePost `json:"favorite_posts,omitempty"`
	// FavoriteQuestions holds the value of the favorite_questions edge.
	FavoriteQuestions []*UserFavoriteQuestion `json:"favorite_questions,omitempty"`
	// Following holds the value of the following edge.
	Following []*Follow `json:"following,omitempty"`
	// FollowedBy holds the value of the followed_by edge.
	FollowedBy []*Follow `json:"followed_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [9]bool
}

// PostsOrErr returns the Posts value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) PostsOrErr() ([]*Post, error) {
	if e.loadedTypes[0] {
		return e.Posts, nil
	}
	return nil, &NotLoadedError{edge: "posts"}
}

// QuestionsOrErr returns the Questions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) QuestionsOrErr() ([]*Question, error) {
	if e.loadedTypes[1] {
		return e.Questions, nil
	}
	return nil, &NotLoadedError{edge: "questions"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[2] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// LikePostsOrErr returns the LikePosts value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) LikePostsOrErr() ([]*UserLikePost, error) {
	if e.loadedTypes[3] {
		return e.LikePosts, nil
	}
	return nil, &NotLoadedError{edge: "like_posts"}
}

// LikeQuestionsOrErr returns the LikeQuestions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) LikeQuestionsOrErr() ([]*UserLikeQuestion, error) {
	if e.loadedTypes[4] {
		return e.LikeQuestions, nil
	}
	return nil, &NotLoadedError{edge: "like_questions"}
}

// FavoritePostsOrErr returns the FavoritePosts value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FavoritePostsOrErr() ([]*UserFavoritePost, error) {
	if e.loadedTypes[5] {
		return e.FavoritePosts, nil
	}
	return nil, &NotLoadedError{edge: "favorite_posts"}
}

// FavoriteQuestionsOrErr returns the FavoriteQuestions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FavoriteQuestionsOrErr() ([]*UserFavoriteQuestion, error) {
	if e.loadedTypes[6] {
		return e.FavoriteQuestions, nil
	}
	return nil, &NotLoadedError{edge: "favorite_questions"}
}

// FollowingOrErr returns the Following value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FollowingOrErr() ([]*Follow, error) {
	if e.loadedTypes[7] {
		return e.Following, nil
	}
	return nil, &NotLoadedError{edge: "following"}
}

// FollowedByOrErr returns the FollowedBy value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FollowedByOrErr() ([]*Follow, error) {
	if e.loadedTypes[8] {
		return e.FollowedBy, nil
	}
	return nil, &NotLoadedError{edge: "followed_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldPhone, user.FieldNickname, user.FieldPassword, user.FieldAvatar:
			values[i] = new(sql.NullString)
		case user.FieldCreateTime, user.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case user.ForeignKeys[0]: // comment_user
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[1]: // follow_follower
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[2]: // follow_following
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[3]: // post_user
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[4]: // question_user
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[5]: // user_favorite_post_user
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[6]: // user_favorite_question_user
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[7]: // user_like_post_user
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[8]: // user_like_question_user
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case user.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				u.CreateTime = value.Time
			}
		case user.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				u.UpdateTime = value.Time
			}
		case user.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				u.Phone = value.String
			}
		case user.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				u.Nickname = value.String
			}
		case user.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				u.Password = value.String
			}
		case user.FieldAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar", values[i])
			} else if value.Valid {
				u.Avatar = value.String
			}
		case user.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field comment_user", value)
			} else if value.Valid {
				u.comment_user = new(int)
				*u.comment_user = int(value.Int64)
			}
		case user.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field follow_follower", value)
			} else if value.Valid {
				u.follow_follower = new(int)
				*u.follow_follower = int(value.Int64)
			}
		case user.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field follow_following", value)
			} else if value.Valid {
				u.follow_following = new(int)
				*u.follow_following = int(value.Int64)
			}
		case user.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field post_user", value)
			} else if value.Valid {
				u.post_user = new(int)
				*u.post_user = int(value.Int64)
			}
		case user.ForeignKeys[4]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field question_user", value)
			} else if value.Valid {
				u.question_user = new(int)
				*u.question_user = int(value.Int64)
			}
		case user.ForeignKeys[5]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_favorite_post_user", value)
			} else if value.Valid {
				u.user_favorite_post_user = new(int)
				*u.user_favorite_post_user = int(value.Int64)
			}
		case user.ForeignKeys[6]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_favorite_question_user", value)
			} else if value.Valid {
				u.user_favorite_question_user = new(int)
				*u.user_favorite_question_user = int(value.Int64)
			}
		case user.ForeignKeys[7]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_like_post_user", value)
			} else if value.Valid {
				u.user_like_post_user = new(int)
				*u.user_like_post_user = int(value.Int64)
			}
		case user.ForeignKeys[8]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_like_question_user", value)
			} else if value.Valid {
				u.user_like_question_user = new(int)
				*u.user_like_question_user = int(value.Int64)
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (u *User) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryPosts queries the "posts" edge of the User entity.
func (u *User) QueryPosts() *PostQuery {
	return NewUserClient(u.config).QueryPosts(u)
}

// QueryQuestions queries the "questions" edge of the User entity.
func (u *User) QueryQuestions() *QuestionQuery {
	return NewUserClient(u.config).QueryQuestions(u)
}

// QueryComments queries the "comments" edge of the User entity.
func (u *User) QueryComments() *CommentQuery {
	return NewUserClient(u.config).QueryComments(u)
}

// QueryLikePosts queries the "like_posts" edge of the User entity.
func (u *User) QueryLikePosts() *UserLikePostQuery {
	return NewUserClient(u.config).QueryLikePosts(u)
}

// QueryLikeQuestions queries the "like_questions" edge of the User entity.
func (u *User) QueryLikeQuestions() *UserLikeQuestionQuery {
	return NewUserClient(u.config).QueryLikeQuestions(u)
}

// QueryFavoritePosts queries the "favorite_posts" edge of the User entity.
func (u *User) QueryFavoritePosts() *UserFavoritePostQuery {
	return NewUserClient(u.config).QueryFavoritePosts(u)
}

// QueryFavoriteQuestions queries the "favorite_questions" edge of the User entity.
func (u *User) QueryFavoriteQuestions() *UserFavoriteQuestionQuery {
	return NewUserClient(u.config).QueryFavoriteQuestions(u)
}

// QueryFollowing queries the "following" edge of the User entity.
func (u *User) QueryFollowing() *FollowQuery {
	return NewUserClient(u.config).QueryFollowing(u)
}

// QueryFollowedBy queries the "followed_by" edge of the User entity.
func (u *User) QueryFollowedBy() *FollowQuery {
	return NewUserClient(u.config).QueryFollowedBy(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return NewUserClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("create_time=")
	builder.WriteString(u.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(u.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(u.Phone)
	builder.WriteString(", ")
	builder.WriteString("nickname=")
	builder.WriteString(u.Nickname)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(u.Password)
	builder.WriteString(", ")
	builder.WriteString("avatar=")
	builder.WriteString(u.Avatar)
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
