// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/predicate"
	"backend/internal/ent/question"
	"backend/internal/ent/user"
	"backend/internal/ent/userfavoritequestion"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserFavoriteQuestionQuery is the builder for querying UserFavoriteQuestion entities.
type UserFavoriteQuestionQuery struct {
	config
	ctx          *QueryContext
	order        []userfavoritequestion.OrderOption
	inters       []Interceptor
	predicates   []predicate.UserFavoriteQuestion
	withUser     *UserQuery
	withQuestion *QuestionQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserFavoriteQuestionQuery builder.
func (ufqq *UserFavoriteQuestionQuery) Where(ps ...predicate.UserFavoriteQuestion) *UserFavoriteQuestionQuery {
	ufqq.predicates = append(ufqq.predicates, ps...)
	return ufqq
}

// Limit the number of records to be returned by this query.
func (ufqq *UserFavoriteQuestionQuery) Limit(limit int) *UserFavoriteQuestionQuery {
	ufqq.ctx.Limit = &limit
	return ufqq
}

// Offset to start from.
func (ufqq *UserFavoriteQuestionQuery) Offset(offset int) *UserFavoriteQuestionQuery {
	ufqq.ctx.Offset = &offset
	return ufqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ufqq *UserFavoriteQuestionQuery) Unique(unique bool) *UserFavoriteQuestionQuery {
	ufqq.ctx.Unique = &unique
	return ufqq
}

// Order specifies how the records should be ordered.
func (ufqq *UserFavoriteQuestionQuery) Order(o ...userfavoritequestion.OrderOption) *UserFavoriteQuestionQuery {
	ufqq.order = append(ufqq.order, o...)
	return ufqq
}

// QueryUser chains the current query on the "user" edge.
func (ufqq *UserFavoriteQuestionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ufqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ufqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ufqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userfavoritequestion.Table, userfavoritequestion.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userfavoritequestion.UserTable, userfavoritequestion.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ufqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryQuestion chains the current query on the "question" edge.
func (ufqq *UserFavoriteQuestionQuery) QueryQuestion() *QuestionQuery {
	query := (&QuestionClient{config: ufqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ufqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ufqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userfavoritequestion.Table, userfavoritequestion.FieldID, selector),
			sqlgraph.To(question.Table, question.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userfavoritequestion.QuestionTable, userfavoritequestion.QuestionColumn),
		)
		fromU = sqlgraph.SetNeighbors(ufqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserFavoriteQuestion entity from the query.
// Returns a *NotFoundError when no UserFavoriteQuestion was found.
func (ufqq *UserFavoriteQuestionQuery) First(ctx context.Context) (*UserFavoriteQuestion, error) {
	nodes, err := ufqq.Limit(1).All(setContextOp(ctx, ufqq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userfavoritequestion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ufqq *UserFavoriteQuestionQuery) FirstX(ctx context.Context) *UserFavoriteQuestion {
	node, err := ufqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserFavoriteQuestion ID from the query.
// Returns a *NotFoundError when no UserFavoriteQuestion ID was found.
func (ufqq *UserFavoriteQuestionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ufqq.Limit(1).IDs(setContextOp(ctx, ufqq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userfavoritequestion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ufqq *UserFavoriteQuestionQuery) FirstIDX(ctx context.Context) int {
	id, err := ufqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserFavoriteQuestion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserFavoriteQuestion entity is found.
// Returns a *NotFoundError when no UserFavoriteQuestion entities are found.
func (ufqq *UserFavoriteQuestionQuery) Only(ctx context.Context) (*UserFavoriteQuestion, error) {
	nodes, err := ufqq.Limit(2).All(setContextOp(ctx, ufqq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userfavoritequestion.Label}
	default:
		return nil, &NotSingularError{userfavoritequestion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ufqq *UserFavoriteQuestionQuery) OnlyX(ctx context.Context) *UserFavoriteQuestion {
	node, err := ufqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserFavoriteQuestion ID in the query.
// Returns a *NotSingularError when more than one UserFavoriteQuestion ID is found.
// Returns a *NotFoundError when no entities are found.
func (ufqq *UserFavoriteQuestionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ufqq.Limit(2).IDs(setContextOp(ctx, ufqq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userfavoritequestion.Label}
	default:
		err = &NotSingularError{userfavoritequestion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ufqq *UserFavoriteQuestionQuery) OnlyIDX(ctx context.Context) int {
	id, err := ufqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserFavoriteQuestions.
func (ufqq *UserFavoriteQuestionQuery) All(ctx context.Context) ([]*UserFavoriteQuestion, error) {
	ctx = setContextOp(ctx, ufqq.ctx, "All")
	if err := ufqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserFavoriteQuestion, *UserFavoriteQuestionQuery]()
	return withInterceptors[[]*UserFavoriteQuestion](ctx, ufqq, qr, ufqq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ufqq *UserFavoriteQuestionQuery) AllX(ctx context.Context) []*UserFavoriteQuestion {
	nodes, err := ufqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserFavoriteQuestion IDs.
func (ufqq *UserFavoriteQuestionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ufqq.ctx.Unique == nil && ufqq.path != nil {
		ufqq.Unique(true)
	}
	ctx = setContextOp(ctx, ufqq.ctx, "IDs")
	if err = ufqq.Select(userfavoritequestion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ufqq *UserFavoriteQuestionQuery) IDsX(ctx context.Context) []int {
	ids, err := ufqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ufqq *UserFavoriteQuestionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ufqq.ctx, "Count")
	if err := ufqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ufqq, querierCount[*UserFavoriteQuestionQuery](), ufqq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ufqq *UserFavoriteQuestionQuery) CountX(ctx context.Context) int {
	count, err := ufqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ufqq *UserFavoriteQuestionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ufqq.ctx, "Exist")
	switch _, err := ufqq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ufqq *UserFavoriteQuestionQuery) ExistX(ctx context.Context) bool {
	exist, err := ufqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserFavoriteQuestionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ufqq *UserFavoriteQuestionQuery) Clone() *UserFavoriteQuestionQuery {
	if ufqq == nil {
		return nil
	}
	return &UserFavoriteQuestionQuery{
		config:       ufqq.config,
		ctx:          ufqq.ctx.Clone(),
		order:        append([]userfavoritequestion.OrderOption{}, ufqq.order...),
		inters:       append([]Interceptor{}, ufqq.inters...),
		predicates:   append([]predicate.UserFavoriteQuestion{}, ufqq.predicates...),
		withUser:     ufqq.withUser.Clone(),
		withQuestion: ufqq.withQuestion.Clone(),
		// clone intermediate query.
		sql:  ufqq.sql.Clone(),
		path: ufqq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ufqq *UserFavoriteQuestionQuery) WithUser(opts ...func(*UserQuery)) *UserFavoriteQuestionQuery {
	query := (&UserClient{config: ufqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ufqq.withUser = query
	return ufqq
}

// WithQuestion tells the query-builder to eager-load the nodes that are connected to
// the "question" edge. The optional arguments are used to configure the query builder of the edge.
func (ufqq *UserFavoriteQuestionQuery) WithQuestion(opts ...func(*QuestionQuery)) *UserFavoriteQuestionQuery {
	query := (&QuestionClient{config: ufqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ufqq.withQuestion = query
	return ufqq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserFavoriteQuestion.Query().
//		GroupBy(userfavoritequestion.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ufqq *UserFavoriteQuestionQuery) GroupBy(field string, fields ...string) *UserFavoriteQuestionGroupBy {
	ufqq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserFavoriteQuestionGroupBy{build: ufqq}
	grbuild.flds = &ufqq.ctx.Fields
	grbuild.label = userfavoritequestion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UserFavoriteQuestion.Query().
//		Select(userfavoritequestion.FieldUserID).
//		Scan(ctx, &v)
func (ufqq *UserFavoriteQuestionQuery) Select(fields ...string) *UserFavoriteQuestionSelect {
	ufqq.ctx.Fields = append(ufqq.ctx.Fields, fields...)
	sbuild := &UserFavoriteQuestionSelect{UserFavoriteQuestionQuery: ufqq}
	sbuild.label = userfavoritequestion.Label
	sbuild.flds, sbuild.scan = &ufqq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserFavoriteQuestionSelect configured with the given aggregations.
func (ufqq *UserFavoriteQuestionQuery) Aggregate(fns ...AggregateFunc) *UserFavoriteQuestionSelect {
	return ufqq.Select().Aggregate(fns...)
}

func (ufqq *UserFavoriteQuestionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ufqq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ufqq); err != nil {
				return err
			}
		}
	}
	for _, f := range ufqq.ctx.Fields {
		if !userfavoritequestion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ufqq.path != nil {
		prev, err := ufqq.path(ctx)
		if err != nil {
			return err
		}
		ufqq.sql = prev
	}
	return nil
}

func (ufqq *UserFavoriteQuestionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserFavoriteQuestion, error) {
	var (
		nodes       = []*UserFavoriteQuestion{}
		withFKs     = ufqq.withFKs
		_spec       = ufqq.querySpec()
		loadedTypes = [2]bool{
			ufqq.withUser != nil,
			ufqq.withQuestion != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, userfavoritequestion.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserFavoriteQuestion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserFavoriteQuestion{config: ufqq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ufqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ufqq.withUser; query != nil {
		if err := ufqq.loadUser(ctx, query, nodes,
			func(n *UserFavoriteQuestion) { n.Edges.User = []*User{} },
			func(n *UserFavoriteQuestion, e *User) { n.Edges.User = append(n.Edges.User, e) }); err != nil {
			return nil, err
		}
	}
	if query := ufqq.withQuestion; query != nil {
		if err := ufqq.loadQuestion(ctx, query, nodes,
			func(n *UserFavoriteQuestion) { n.Edges.Question = []*Question{} },
			func(n *UserFavoriteQuestion, e *Question) { n.Edges.Question = append(n.Edges.Question, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ufqq *UserFavoriteQuestionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserFavoriteQuestion, init func(*UserFavoriteQuestion), assign func(*UserFavoriteQuestion, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*UserFavoriteQuestion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(userfavoritequestion.UserColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.user_favorite_question_user
		if fk == nil {
			return fmt.Errorf(`foreign-key "user_favorite_question_user" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_favorite_question_user" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (ufqq *UserFavoriteQuestionQuery) loadQuestion(ctx context.Context, query *QuestionQuery, nodes []*UserFavoriteQuestion, init func(*UserFavoriteQuestion), assign func(*UserFavoriteQuestion, *Question)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*UserFavoriteQuestion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Question(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(userfavoritequestion.QuestionColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.user_favorite_question_question
		if fk == nil {
			return fmt.Errorf(`foreign-key "user_favorite_question_question" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_favorite_question_question" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ufqq *UserFavoriteQuestionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ufqq.querySpec()
	_spec.Node.Columns = ufqq.ctx.Fields
	if len(ufqq.ctx.Fields) > 0 {
		_spec.Unique = ufqq.ctx.Unique != nil && *ufqq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ufqq.driver, _spec)
}

func (ufqq *UserFavoriteQuestionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userfavoritequestion.Table, userfavoritequestion.Columns, sqlgraph.NewFieldSpec(userfavoritequestion.FieldID, field.TypeInt))
	_spec.From = ufqq.sql
	if unique := ufqq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ufqq.path != nil {
		_spec.Unique = true
	}
	if fields := ufqq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userfavoritequestion.FieldID)
		for i := range fields {
			if fields[i] != userfavoritequestion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ufqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ufqq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ufqq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ufqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ufqq *UserFavoriteQuestionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ufqq.driver.Dialect())
	t1 := builder.Table(userfavoritequestion.Table)
	columns := ufqq.ctx.Fields
	if len(columns) == 0 {
		columns = userfavoritequestion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ufqq.sql != nil {
		selector = ufqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ufqq.ctx.Unique != nil && *ufqq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ufqq.predicates {
		p(selector)
	}
	for _, p := range ufqq.order {
		p(selector)
	}
	if offset := ufqq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ufqq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserFavoriteQuestionGroupBy is the group-by builder for UserFavoriteQuestion entities.
type UserFavoriteQuestionGroupBy struct {
	selector
	build *UserFavoriteQuestionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ufqgb *UserFavoriteQuestionGroupBy) Aggregate(fns ...AggregateFunc) *UserFavoriteQuestionGroupBy {
	ufqgb.fns = append(ufqgb.fns, fns...)
	return ufqgb
}

// Scan applies the selector query and scans the result into the given value.
func (ufqgb *UserFavoriteQuestionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ufqgb.build.ctx, "GroupBy")
	if err := ufqgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserFavoriteQuestionQuery, *UserFavoriteQuestionGroupBy](ctx, ufqgb.build, ufqgb, ufqgb.build.inters, v)
}

func (ufqgb *UserFavoriteQuestionGroupBy) sqlScan(ctx context.Context, root *UserFavoriteQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ufqgb.fns))
	for _, fn := range ufqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ufqgb.flds)+len(ufqgb.fns))
		for _, f := range *ufqgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ufqgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ufqgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserFavoriteQuestionSelect is the builder for selecting fields of UserFavoriteQuestion entities.
type UserFavoriteQuestionSelect struct {
	*UserFavoriteQuestionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ufqs *UserFavoriteQuestionSelect) Aggregate(fns ...AggregateFunc) *UserFavoriteQuestionSelect {
	ufqs.fns = append(ufqs.fns, fns...)
	return ufqs
}

// Scan applies the selector query and scans the result into the given value.
func (ufqs *UserFavoriteQuestionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ufqs.ctx, "Select")
	if err := ufqs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserFavoriteQuestionQuery, *UserFavoriteQuestionSelect](ctx, ufqs.UserFavoriteQuestionQuery, ufqs, ufqs.inters, v)
}

func (ufqs *UserFavoriteQuestionSelect) sqlScan(ctx context.Context, root *UserFavoriteQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ufqs.fns))
	for _, fn := range ufqs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ufqs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ufqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
