// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/userlikepost"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserLikePost is the model entity for the UserLikePost schema.
type UserLikePost struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID int `json:"post_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserLikePostQuery when eager-loading is set.
	Edges           UserLikePostEdges `json:"edges"`
	post_likes      *int
	user_like_posts *int
	selectValues    sql.SelectValues
}

// UserLikePostEdges holds the relations/edges for other nodes in the graph.
type UserLikePostEdges struct {
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// Post holds the value of the post edge.
	Post []*Post `json:"post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e UserLikePostEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading.
func (e UserLikePostEdges) PostOrErr() ([]*Post, error) {
	if e.loadedTypes[1] {
		return e.Post, nil
	}
	return nil, &NotLoadedError{edge: "post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserLikePost) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userlikepost.FieldID, userlikepost.FieldUserID, userlikepost.FieldPostID:
			values[i] = new(sql.NullInt64)
		case userlikepost.ForeignKeys[0]: // post_likes
			values[i] = new(sql.NullInt64)
		case userlikepost.ForeignKeys[1]: // user_like_posts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserLikePost fields.
func (ulp *UserLikePost) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userlikepost.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ulp.ID = int(value.Int64)
		case userlikepost.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ulp.UserID = int(value.Int64)
			}
		case userlikepost.FieldPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				ulp.PostID = int(value.Int64)
			}
		case userlikepost.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field post_likes", value)
			} else if value.Valid {
				ulp.post_likes = new(int)
				*ulp.post_likes = int(value.Int64)
			}
		case userlikepost.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_like_posts", value)
			} else if value.Valid {
				ulp.user_like_posts = new(int)
				*ulp.user_like_posts = int(value.Int64)
			}
		default:
			ulp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserLikePost.
// This includes values selected through modifiers, order, etc.
func (ulp *UserLikePost) Value(name string) (ent.Value, error) {
	return ulp.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserLikePost entity.
func (ulp *UserLikePost) QueryUser() *UserQuery {
	return NewUserLikePostClient(ulp.config).QueryUser(ulp)
}

// QueryPost queries the "post" edge of the UserLikePost entity.
func (ulp *UserLikePost) QueryPost() *PostQuery {
	return NewUserLikePostClient(ulp.config).QueryPost(ulp)
}

// Update returns a builder for updating this UserLikePost.
// Note that you need to call UserLikePost.Unwrap() before calling this method if this UserLikePost
// was returned from a transaction, and the transaction was committed or rolled back.
func (ulp *UserLikePost) Update() *UserLikePostUpdateOne {
	return NewUserLikePostClient(ulp.config).UpdateOne(ulp)
}

// Unwrap unwraps the UserLikePost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ulp *UserLikePost) Unwrap() *UserLikePost {
	_tx, ok := ulp.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserLikePost is not a transactional entity")
	}
	ulp.config.driver = _tx.drv
	return ulp
}

// String implements the fmt.Stringer.
func (ulp *UserLikePost) String() string {
	var builder strings.Builder
	builder.WriteString("UserLikePost(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ulp.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ulp.UserID))
	builder.WriteString(", ")
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", ulp.PostID))
	builder.WriteByte(')')
	return builder.String()
}

// UserLikePosts is a parsable slice of UserLikePost.
type UserLikePosts []*UserLikePost
