// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/userlikequestion"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserLikeQuestion is the model entity for the UserLikeQuestion schema.
type UserLikeQuestion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// QuestionID holds the value of the "question_id" field.
	QuestionID int `json:"question_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserLikeQuestionQuery when eager-loading is set.
	Edges               UserLikeQuestionEdges `json:"edges"`
	question_likes      *int
	user_like_questions *int
	selectValues        sql.SelectValues
}

// UserLikeQuestionEdges holds the relations/edges for other nodes in the graph.
type UserLikeQuestionEdges struct {
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// Question holds the value of the question edge.
	Question []*Question `json:"question,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e UserLikeQuestionEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading.
func (e UserLikeQuestionEdges) QuestionOrErr() ([]*Question, error) {
	if e.loadedTypes[1] {
		return e.Question, nil
	}
	return nil, &NotLoadedError{edge: "question"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserLikeQuestion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userlikequestion.FieldID, userlikequestion.FieldUserID, userlikequestion.FieldQuestionID:
			values[i] = new(sql.NullInt64)
		case userlikequestion.ForeignKeys[0]: // question_likes
			values[i] = new(sql.NullInt64)
		case userlikequestion.ForeignKeys[1]: // user_like_questions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserLikeQuestion fields.
func (ulq *UserLikeQuestion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userlikequestion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ulq.ID = int(value.Int64)
		case userlikequestion.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ulq.UserID = int(value.Int64)
			}
		case userlikequestion.FieldQuestionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field question_id", values[i])
			} else if value.Valid {
				ulq.QuestionID = int(value.Int64)
			}
		case userlikequestion.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field question_likes", value)
			} else if value.Valid {
				ulq.question_likes = new(int)
				*ulq.question_likes = int(value.Int64)
			}
		case userlikequestion.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_like_questions", value)
			} else if value.Valid {
				ulq.user_like_questions = new(int)
				*ulq.user_like_questions = int(value.Int64)
			}
		default:
			ulq.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserLikeQuestion.
// This includes values selected through modifiers, order, etc.
func (ulq *UserLikeQuestion) Value(name string) (ent.Value, error) {
	return ulq.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserLikeQuestion entity.
func (ulq *UserLikeQuestion) QueryUser() *UserQuery {
	return NewUserLikeQuestionClient(ulq.config).QueryUser(ulq)
}

// QueryQuestion queries the "question" edge of the UserLikeQuestion entity.
func (ulq *UserLikeQuestion) QueryQuestion() *QuestionQuery {
	return NewUserLikeQuestionClient(ulq.config).QueryQuestion(ulq)
}

// Update returns a builder for updating this UserLikeQuestion.
// Note that you need to call UserLikeQuestion.Unwrap() before calling this method if this UserLikeQuestion
// was returned from a transaction, and the transaction was committed or rolled back.
func (ulq *UserLikeQuestion) Update() *UserLikeQuestionUpdateOne {
	return NewUserLikeQuestionClient(ulq.config).UpdateOne(ulq)
}

// Unwrap unwraps the UserLikeQuestion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ulq *UserLikeQuestion) Unwrap() *UserLikeQuestion {
	_tx, ok := ulq.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserLikeQuestion is not a transactional entity")
	}
	ulq.config.driver = _tx.drv
	return ulq
}

// String implements the fmt.Stringer.
func (ulq *UserLikeQuestion) String() string {
	var builder strings.Builder
	builder.WriteString("UserLikeQuestion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ulq.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ulq.UserID))
	builder.WriteString(", ")
	builder.WriteString("question_id=")
	builder.WriteString(fmt.Sprintf("%v", ulq.QuestionID))
	builder.WriteByte(')')
	return builder.String()
}

// UserLikeQuestions is a parsable slice of UserLikeQuestion.
type UserLikeQuestions []*UserLikeQuestion
