// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Follow is the predicate function for follow builders.
type Follow func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// PostTag is the predicate function for posttag builders.
type PostTag func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// QuestionTag is the predicate function for questiontag builders.
type QuestionTag func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserFavoritePost is the predicate function for userfavoritepost builders.
type UserFavoritePost func(*sql.Selector)

// UserFavoriteQuestion is the predicate function for userfavoritequestion builders.
type UserFavoriteQuestion func(*sql.Selector)

// UserLikePost is the predicate function for userlikepost builders.
type UserLikePost func(*sql.Selector)

// UserLikeQuestion is the predicate function for userlikequestion builders.
type UserLikeQuestion func(*sql.Selector)
